### **NumPy Foundation**

**What is NumPy?**

NumPy ka full form **Numerical Python** hai. Yeh Python ki core open-source library hai jo scientific computing, data analysis aur Machine Learning me mathematical operations handle karne ke liye use hoti hai.

Iska main hero object hota hai **`ndarray`** (N-dimensional Array)—ek aisi grid jo 1D (vectors), 2D (matrices), ya multi-dimensional data ko store aur manipulate karti hai.

---

**Why Use NumPy? (Python List vs NumPy)**

Python me built-in `list` pehle se hoti hai, phir bhi hum Data Science aur AI me NumPy use karte hain. Iske 4 main reasons hain:

* **Extreme Speed (Fast Execution) :-** Python lists pure Python code par chalti hain jo slow hota hai. NumPy internally **C aur C++** me likha gaya hai, isliye iske calculations C-level speed par execute hote hain.

* **Contiguous Memory Storage :-** Python list memory me scattered (bikhre hue) pointers store karti hai, jisse CPU cache miss hota hai. NumPy array saare numbers ko memory me **lagaatar (contiguous memory blocks)** store karta hai, jisse data fetch karna super-fast ho jata hai.

* **Homogeneous Data :-** Python list me aap int, string, float mix kar sakte ho, jiski wajah se Python ko har element ka type baar-baar check karna padta hai. NumPy me sirf ek hi data type hota hai (homogeneous), isliye koi overhead nahi hota.

* **Vectorized Operations (No For-Loops) :-** List me do collections ko add karne ke liye `for` loop chalana padta hai. NumPy me bina loop likhe direct mathematical calculation hoti hai (e.g., `a + b`), jo CPU level par parallel execute hoti hai.

* **Linear Algebra & AI Ready :-** Machine Learning aur Neural Networks ke basic building blocks—jaise Dot Products, Matrix Multiplications, aur Transpose—NumPy me built-in optimize hote hain.

---

**NumPy Architecture: Key Concepts**

* **Scalars (0D) :-** Ek single value ya number.

* **Vectors (1D) :-** Ek flat list jaisa array jisme sirf ek dimension (length) hoti hai.

* **Matrices (2D) :-** Rows aur columns ka format, jo tabular datasets aur model weights store karne ke kaam aata hai.

* **Tensors (3D+) :-** Multiple matrices ka stack, jaise color images (Height × Width × RGB channels).

---

**Array Metadata Attributes (Array ki pehchan kaise karein)**

* **Shape :-** Batata hai array ka layout kaisa hai (e.g., `(3, 4)` matlab 3 rows aur 4 columns).

* **Dimensions (`ndim`) :-** Batata hai array kitne dimensional hai (1D, 2D, ya 3D).

* **Size :-** Pure array ke andar total elements ki sankhya batata hai.

* **Data Type (`dtype`) :-** Elements ka type specify karta hai (e.g., `int32`, `float64`).

---

**NumPy Core Features (Exam & Interview Summary)**

* **Broadcasting :-** Jab do alag-alag shapes ke arrays par calculation karni ho, toh NumPy automatically smaller array ko stretch karke match kar leta hai.

* **Slicing & Indexing :-** Kisi bade dataset ya matrix me se specific rows, columns ya sub-matrices ko bina copy banaye view format me fast extract karna.

* **Aggregation Functions :-** Puri matrix ya kisi specific row/column ka direct `mean`, `sum`, `std`, `min`, aur `max` calculate karna.

In [1]:
import numpy as np

### **Array**
An array is a collection of elements of the same data type stored in memory.

**Syntax**:-  np.array(object)

In [2]:
lst = [12, 43, 54, 64, 13, 32, 43, 89]

arr = np.array(lst)

### **ndarray**
ndarray is the main object in NumPy representing an N-dimensional array.

**Syntax**:- type(array)

In [3]:
type(arr)

numpy.ndarray

### **Shape**
Shape represents the dimensions (rows, columns) of an array.

**Syntax**:-  array.shape

In [4]:
arr.shape

(8,)

### **Data Type (dtype)**
Defines the type of elements stored in the array.

**Syntax**:-  array.dtype

In [5]:
arr.dtype

dtype('int64')

### **Reshape**
Used to change the shape of an array without changing data.

**Syntax**:-  array.reshape(rows, columns)

In [6]:
a = arr.reshape(2, 4)
a

array([[12, 43, 54, 64],
       [13, 32, 43, 89]])

### **Flatening the array**
Converts multi-dimensional array into 1D array.

**Syntax**:-  array.reshape(-1)

In [7]:
a.reshape(-1)

array([12, 43, 54, 64, 13, 32, 43, 89])

### **Dimensions (ndim)**
`ndim` batata hai ki array kitne dimensions ka hai (yaani total kitni axes hain: 1D vector, 2D matrix, ya 3D block).

* Inshort yeh batata hai ki data kitne layers/brackets me packed hai.

**Syntax** :- array.ndim

- 1D array ke liye output aayega: `1`
- 2D array ke liye output aayega: `2`
- 3D array ke liye output aayega: `3`

In [8]:
# ndim check karne ke examples
d1 = np.array([10, 20, 30])
d2 = np.array([[1, 2, 3], [4, 5, 6]])
d3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"d1 dimension : {d1.ndim}")
print(f"d2 dimension : {d2.ndim}")
print(f"d3 dimension : {d3.ndim}")

d1 dimension : 1
d2 dimension : 2
d3 dimension : 3


### **Size**
`size` attribute pure array ke andar present total elements ki exact sankhya (count) return karta hai.

* Inshort yeh `shape` ke sabhi dimensions ka product hota hai (Rows × Columns).

**Syntax** :- array.size

Example: Agar shape `(3, 4)` hai toh size $3 \times 4 = 12$ hoga.

In [9]:
# size check karne ke examples
matrix = np.array([[10, 20, 30, 40], 
                   [50, 60, 70, 80], 
                   [90, 100, 110, 120]])

print("Matrix:\n", matrix)
print()
print(f"Shape of matrix : {matrix.shape}")
print(f"Total elements (size) : {matrix.size}")

Matrix:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Shape of matrix : (3, 4)
Total elements (size) : 12


### **Zeros**
--> It is an inbuilt function which is used to create an array of only zero. 
* It uesd **Placeholder** or **strating point** before filling real data. 

Example - **Empty attendence sheet**

* Inshort it means no Data yet

**Syntax** :- np.zeros(dimensions)

- for 1-D array shape is np.zeros(v)
- for 2-D array shape is np.zeros(r,v)
- for 3-D array shape is np.zeros(n,r,v)

In [10]:
b = np.zeros(5)
b

array([0., 0., 0., 0., 0.])

In [11]:
b = np.zeros((3, 5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
b = np.zeros((3, 3, 4))
b

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### **Ones**
--> It is an inbuilt function which is used to create an array of only zero. 
* It uesd to give ge defualt value as start and lter fill. 

Example - **Mark all products as available**

* Inshort it is used to fill data with equal value by defualt.

**Syntax** :- np.ones(dimensions)

- for 1-D array shape is np.ones(v)
- for 2-D array shape is np.ones(r,v)
- for 3-D array shape is np.ones(n,r,v)

In [13]:
one = np.ones(4)
one

array([1., 1., 1., 1.])

In [14]:
one = np.ones((2, 5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
one = np.ones((3, 3, 5))
one

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### **Full**
--> Yeh ek inbuilt function hai jo specified shape ka array banata hai aur use kisi specific constant value se fill karta hai.
* Jaise `np.zeros()` me 0 aur `np.ones()` me 1 fill hota hai, `np.full()` me hum apni pasand ka koi bhi number fill kar sakte hain.

Example - **Default base score set karna har player ka**

**Syntax** :- np.full(shape, fill_value)

- `shape`: (rows, cols) ya single integer
- `fill_value`: Jo value har jagah fill karni hai

In [16]:
# 1D array filled with 9
full_1d = np.full(5, 9)
print("1D Full Array:\n", full_1d)

print()

# 2D array (3x4) filled with 42
full_2d = np.full((3, 4), 42)
print("2D Full Array (3x4):\n", full_2d)

print()

# 2D array filled with float value 3.14
full_float = np.full((2, 3), 3.14)
print("2D Full Array with float:\n", full_float)

1D Full Array:
 [9 9 9 9 9]

2D Full Array (3x4):
 [[42 42 42 42]
 [42 42 42 42]
 [42 42 42 42]]

2D Full Array with float:
 [[3.14 3.14 3.14]
 [3.14 3.14 3.14]]


### **Identity Matrix**
Creates a square matrix with diagonal elements as 1.

**Syntax**:-np.identity(n)

- where n is the value of square marix

In [17]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### **linspace()**
--> It is used to generate equally spaced values between the specified limits

**Syntax** :- np.linspace(sv, ev,n)
- where n is the values to be generated.
- ev is included in the class of linspce function.
- if n is not specified by defailt it will generate 50 vlaues.

In [18]:
lin = np.linspace(1, 10, 50)
lin

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

### **Randint()**
It is used to genereate random numbers between the specified limits.

**Syntax** :- np.random.randint(sv,ev,n)
- where n(optional) is the values to be generated.
- sv and ev both are included in the clase of random module.
- if n is not specified by default it will gerenate 1 value.

In [19]:
ran = np.random.randint(1, 10, 20)
ran

array([2, 6, 3, 9, 8, 5, 3, 3, 8, 2, 3, 1, 6, 8, 9, 6, 1, 6, 9, 8],
      dtype=int32)

In [20]:
np.random.randint(1, 25, 5)

array([15,  1, 23, 16,  7], dtype=int32)

### **randn()**
It is used to generate floating values between + infinity to - infinity

**Syntax** :- np.random.randn(n)
- where n(optional) is the values to be generated.
- if n is not specified by default it will gerenate 1 value.

In [21]:
np.random.randn(10)

array([-0.46775876, -0.23441594,  0.04994199,  0.0460173 ,  0.68113224,
        1.40571098, -0.34812442, -1.26015238, -0.38511238,  0.66381289])

### **Copy Opteration**
there are three types of copy operation in the case of numpy array:
1) normal copy
2) copy()
3) view ()

### 1) **Normal Copy**
In the case of normal copy since both of the array will be pointing to the same address change made in the original array will affecr the copy and vice versa.

**Syntax** :- 
- arr = np.array 
- arr2 = arr

In [22]:
arr

array([12, 43, 54, 64, 13, 32, 43, 89])

In [23]:
arr2 = arr
print(arr2)
print(id(arr))
print(id(arr2))

[12 43 54 64 13 32 43 89]
1450543639280
1450543639280


In [24]:
arr[0] = 100
arr2[1] = 200
print(arr)
print(arr2)

[100 200  54  64  13  32  43  89]
[100 200  54  64  13  32  43  89]


### 2)  Copy()
in the case ofcopy, copy owns the dataand any changes amde to the copy will not affect originial array, and any changes made to the original array will not affect the code.

**Reason**:- The reason is beacuse both of the arrays will be pointing to difference address even though the values stroed are same.

**Syntax** :-
- arr = np.array()
- arr2 = arr.copy()

In [25]:
arr3 = arr2.copy()
arr3

array([100, 200,  54,  64,  13,  32,  43,  89])

In [26]:
print(id(arr2))
print(id(arr3))

1450543639280
1450915886256


In [27]:
arr2[-1] = 100
arr3[-2] = 200
print(arr2)
print(arr3)

[100 200  54  64  13  32  43 100]
[100 200  54  64  13  32 200  89]


### 3) View ()
in the case of the view the copy as well as  array both will be having a diiferent address but still modification done in the original array will be affect the copy.

**Syntax**:- array.view()

In [28]:
arr4 = arr3.view()
arr4

array([100, 200,  54,  64,  13,  32, 200,  89])

In [29]:
print(id(arr3))
print(id(arr4))

1450915886256
1450915872912


In [30]:
arr3[4] = 0
arr4[5] = 98
print(arr3)
print(arr4)

[100 200  54  64   0  98 200  89]
[100 200  54  64   0  98 200  89]


### **Assignment**

In [31]:

#! Python list [10, 20, 30, 40] ko int32 type ke NumPy array me convert karein.  
lst = [10, 20, 30, 40]
arr = np.array(lst, dtype = np.int32)
print(f"Array : {arr}") 

#! Ek shape (4, 5) ka array banayein jisme sabhi elements sirf 0. hon.   
arr2 = np.zeros((4, 5))
print(f"\nZero's Array : \n{arr2}")

#! Ek 1D array banayein jisme 8 elements hon aur sabhi values 1. hon.   
arr3 = np.ones(8)
print(f"\nOnces Array : \n{arr3}")

#! Ek 2D array (3, 3) create karein jisme har position par number 7 filled ho using np.full().   
arr4 = np.full(9, fill_value = 7).reshape(3, 3)
print(f"\n7's Array : \n{arr4}")

#! 1 se lekar 50 tak ke sabhi even numbers ka 1D array banayein using np.arange().   
arr5 = np.arange(1, 51, 2)
print(f"\nEven Number Array : \n{arr5}")  

Array : [10 20 30 40]

Zero's Array : 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Onces Array : 
[1. 1. 1. 1. 1. 1. 1. 1.]

7's Array : 
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Even Number Array : 
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [32]:

#! 0 se 1 ke beech exactly 5 linearly spaced floating numbers generate karein using np.linspace(). 
arr6 = np.linspace(0, 1, 5)
print(f"Linspace Array : {arr6}")  

#! Ek 5x5 identity matrix create karein using np.identity().   
arr7 = np.identity(5)
print(f"\nIdentity Matrix Array : \n{arr7}")

#! Ek random 1D array banayein jisme 10 se 50 ke beech ke 10 integers hon using np.random.randint().   
arr8 = np.random.randint(10, 51, size = 10)
print(f"\nRandom Array : {arr8}")

#! Standard normal distribution se 6 random numbers generate karein using np.random.randn(). 
arr9 = np.random.randn(6)
print(f"\nStandard Normal Distribution Array : {arr9}")  

#! Ek array banayein aur uske chaar attributes print karein: shape, ndim, size, aur dtype.   
print(f"\n{arr4}")
print(f"Array SHape : {arr4.shape}")
print(f"Array Dimenssion : {arr4.ndim}")
print(f"Array Size : {arr4.size}")
print(f"Array DataType : {arr4.dtype}")

Linspace Array : [0.   0.25 0.5  0.75 1.  ]

Identity Matrix Array : 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Random Array : [30 24 16 50 47 41 19 43 37 19]

Standard Normal Distribution Array : [ 1.93650194 -0.94776638  1.48266099 -0.53904303  0.87603295 -0.30139877]

[[7 7 7]
 [7 7 7]
 [7 7 7]]
Array SHape : (3, 3)
Array Dimenssion : 2
Array Size : 9
Array DataType : int64


In [ ]:

#! Kisi array ka total memory consumption bytes me calculate karein using itemsize aur size. 
print(arr3) 
print(f"Array Total Memory Consumption : {arr3.itemsize * arr3.size} bytes")
  
#! Diye gaye array a = np.array([1, 2, 3]) ko variable b = a assign karein; b[0] = 99 karke check karein ki a par kya effect hua.  
a = np.array([1, 2, 3])
b = a
b[0] = 99
print(f"\nWhen we assign a variable to another variable, any change in the assigned variable will affect the original variable : {a}")
 
#! Array a ki ek independent copy banayein using .copy(); copy me change karke verify karein ki original array intact hai.
c = a.copy()
c[0] = 9
print(f"\nWhen we create a copy of an array, changes in the copy do not affect the original array : {a}")

#! Array a ka ek view banayein using .view(); .base attribute print karke verify karein ki yeh view hai.   
d = a.view()
d[0] = 19
print(f"\nWhen we create a view of an array, changes in the view affect the original array : {a}")

#! Float numbers ka array create karein aur use .astype(np.int32) se integer me convert karein.
arr15 = np.array([1.5, 2.7, 3.9, 4.2])
arr15_int = arr15.astype(np.int32)
print(f"\nChange Array Datatype float into integer : {arr15_int}")


[1. 1. 1. 1. 1. 1. 1. 1.]
Array Total Memory Consumption : 64 bytes

It's Automatically update the value in the array of a : [99  2  3]

It's can not effect/update in the array of  a : [99  2  3]

It's Automatically update the value in the array of a : [19  2  3]

Change Array Datatype float into integer : [1 2 3 4]


In [34]:

#! Ek 3D array create karein shape (2, 2, 2) aur uska ndim print karein. 
arr16 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"3D Array : \n{arr16} \nCheck Array Dimenssion : {arr16.ndim}")

#! Ek empty uninitialized array banayein shape (2, 3) using np.empty().
arr17 = np.empty((2, 3))
print(f"\nEmpty Array : \n{arr17}")

#! Diye gaye 1D array [5, 10, 15] ko diagonal par rakh kar ek 2D diagonal matrix banayein using np.diag(). 
arr18 = np.array([5, 10, 15])
arr18_diagonal = np.diag(arr18)
print(f"\nDiagonal Array : \n{arr18_diagonal}")

#! np.ones() se array banayein aur verify karein ki uska default dtype kya hota hai. 
print(f"\nOnecs Array : {arr3} \ncheck by Defualt data type : {arr3.dtype}")

#! Do alag arrays banayein aur unka memory address id() print karke compare karein. 
print(f"\nZero's Array : \n{arr2} \nand it's id : {id(arr2)}")
print(f"\nOnce's Array : {arr3} \nand it's id : {id(arr3)}")

3D Array : 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
Check Array Dimenssion : 3

Empty Array : 
[[1.93650194 0.94776638 1.48266099]
 [0.53904303 0.87603295 0.30139877]]

Diagonal Array : 
[[ 5  0  0]
 [ 0 10  0]
 [ 0  0 15]]

Onecs Array : [1. 1. 1. 1. 1. 1. 1. 1.] 
check by Defualt data type : float64

Zero's Array : 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 
and it's id : 1450915887216

Once's Array : [1. 1. 1. 1. 1. 1. 1. 1.] 
and it's id : 1450915887408
