## **NumPy Indexing & Slicinging**

NumPy me Indexing aur Slicing ka use arrays ke specific elements, rows, columns aur sub-arrays ko access aur extract karne ke liye hota hai.

Ye concept 1D arrays, 2D matrices aur 3D+ arrays/tensors ke saath kaam karte waqt bahut important hai.

### **NumPy Indexing**

Indexing ka matlab hai array ke andar se specific element ko uske index number ki help se access karna.

**0-Based Indexing**

NumPy me indexing 0 se start hoti hai.

**Example:**

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])

print(arr[2])

**Output:**

10

30

**Yahan:**

10 → index 0

20 → index 1

30 → index 2

40 → index 3

50 → index 4

**Negative Indexing**

Negative indexing ka use array ko right se left access karne ke liye hota hai.

1 → Last element

2 → Second-last element

3 → Third-last element

**Example:**

print(arr[-1])

print(arr[-2])

**Output:**

50

40


### **Basic Indexing in 1D Array**

1D array me ek element ko access karne ke liye:

**Syntax:**

array[index]

**Example:**

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])

print(arr[3])

In [30]:
import numpy as np

lst = [12, 43, 54, 64, 13, 32, 43, 89]

arr = np.array(lst)
arr

array([12, 43, 54, 64, 13, 32, 43, 89])

In [31]:
# Example :- 1-D
# i want to access 3 index value
# i want to access last index value

print(f"I want to access 3 index value : {arr[2]}")
print(f"I want to access last index value : {arr[-1]}")

I want to access 3 index value : 54
I want to access last index value : 89


### **Basic Indexing in 2D Array**

2D array me data rows aur columns ke form me hota hai.

**Syntax:**

array[row_index, column_index]

**Example:**

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])


print(arr[0, 1])

print(arr[2, 0])

**Output:**

20

70

**Yahan:**

arr[0, 1] → Row 0, Column 1

arr[2, 0] → Row 2, Column 0

Note: NumPy me 2D indexing ke liye arr[row, column] likhna preferred hai.

In [32]:
# Example :- -2D
# i want to access the second row second index
# i want to access the last row second last index

d_2 = np.array([[34, 64, 39], 
                [43, 74, 98]])
print(d_2)

print()

print(f"I want to access the second row second index : {d_2[1, 1]}")
print(f"I want to access the second row second index : {d_2[1][1]}")

print()

print(f"I want to access the last row second last index : {d_2[-1, -1]}")
print(f"I want to access the last row second last index : {d_2[-1][-1]}")

[[34 64 39]
 [43 74 98]]

I want to access the second row second index : 74
I want to access the second row second index : 74

I want to access the last row second last index : 98
I want to access the last row second last index : 98


### **Basic Indexing in 3D Array**

3D array ko samajhne ke liye ise multiple 2D matrices ka collection samajh sakte ho.

**Syntax:**

array[matrix_index, row_index, column_index]

**Example:**

arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(arr[0, 1, 2])

**Output:**

6

**Yahan:**

0 → Matrix index

1 → Row index

2 → Column index

**Isliye:**

arr[0, 1, 2]

**ka matlab hai:**

Matrix 0 → Row 1 → Column 2

In [33]:
# Example :- -3D
# i want to access first 2-D array second row middle value
# i want to access second 2-D array first row middle value

d_3 = np.array([[[73, 24, 53], [35, 64, 39]], 
                [[83, 93, 11], [98, 53, 89]]])
print(d_3)

print()

print(f"I want to access first 2-D array second row middle value : {d_3[0, 1, 1]}")
print(f"I want to access first 2-D array second row middle value : {d_3[0][1][1]}")

print()

print(f"I want to access second 2-D array first row middle value : {d_3[1, 0, 1]}")
print(f"I want to access second 2-D array first row middle value : {d_3[1][0][1]}")

[[[73 24 53]
  [35 64 39]]

 [[83 93 11]
  [98 53 89]]]

I want to access first 2-D array second row middle value : 64
I want to access first 2-D array second row middle value : 64

I want to access second 2-D array first row middle value : 93
I want to access second 2-D array first row middle value : 93


### **NumPy Slicing**

Slicing ka matlab hai array ke ek part / range / sub-array ko extract karna.

Slicing ka use ek ya multiple elements ko ek saath access karne ke liye hota hai.

### **Slicing Syntax**
**1D Array**
array[start : stop : step]


#### Parameters

**start (Inclusive)**
Jahan se slicing start hogi. Ye index include hota hai.

**stop (Exclusive)**
Jahan slicing stop hogi. Ye index include nahi hota.

**step**
Har kitne index ke baad element select karna hai.

**Default values:**

start → beginning

stop  → end

step  → 1

**Example:**

arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])

**Output:**

[20 30 40]

**Yahan:**

start = 1

stop  = 4

Index 4 include nahi hoga.

### **1D Array Slicing**

**Syntax:**

arr[start : stop : step]

**Example:**

arr = np.arange(1, 11)

print(arr[2:7])

**Output:**

[3 4 5 6 7]

Step ke saath

print(arr[1:9:2])

**Output:**

[2 4 6 8]

Yahan step = 2 hai, isliye har second element select hoga.

### **Negative Slicing**

Negative indexing ke saath slicing bhi kar sakte hain.

**Example:**

arr = np.array([10, 20, 30, 40, 50])

print(arr[-4:-1])

**Output:**

[20 30 40]

### **Reverse an Array**

Array ko reverse karne ke liye:

arr[::-1]

**Example:**

arr = np.array([10, 20, 30, 40, 50])

print(arr[::-1])

**Output:**

[50 40 30 20 10]

**Yahan:**

start → omitted

stop  → omitted

step  → -1

In [34]:
a1 = np.arange(10, 21)
print(a1)

print()

# 1-D slicing

# I want to access 12, 13, 14
print(a1[2 : 5])

# I want to access 18, 19, 20
print(a1[8 : ])

# I want to access 18, 19, 20
print(a1[-3 : ])

[10 11 12 13 14 15 16 17 18 19 20]

[12 13 14]
[18 19 20]
[18 19 20]


## **Multidimensional Array Slicing**

### **2D Array Slicing**

2D array me hum rows aur columns dono ko slice kar sakte hain.

**Syntax:**

array[row_slice, column_slice]

Example:

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print(arr[0:2, 1:3])

**Output:**

[[20 30]
 [60 70]]

Yahan:

0:2 → Row 0 and Row 1

1:3 → Column 1 and Column 2

### **Selecting Complete Rows**

Agar kisi complete row ko access karna hai:

print(arr[1, :])

**Output:**

[50 60 70 80]

**Yahan :** ka matlab hai all columns.

### **Selecting Complete Columns**

Agar kisi complete column ko access karna hai:

print(arr[:, 2])

**Output:**

[30 70 110]

**Yahan:**

: → all rows

2 → column 2


In [35]:
# 2-D slicing

a2 = np.arange(1, 31).reshape(2, 15)
print(a2)

print()

# I want to access 11 to 14
print(f"I want to access 11 to 14 : {a2[0, 10 : 14]}")

# I want to access 11 to 14
print(f"I want to access 11 to 14 : {a2[0][10 : 14]}")

# I want to access 30 to 21
print(f"I want to access 30 to 21 : {a2[1, -1 : -11 : -1]}")

# I want to access 30 to 21
print(f"I want to access 30 to 21 : {a2[1][-1 : -11 : -1]}")

# I want to access first row 5 - 10 and second row 20 - 25
print(f"I want to access first row 5 to 10 and second row 20 to 25 :")
print(f"{a2[:, 4 : 10]}")

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]

I want to access 11 to 14 : [11 12 13 14]
I want to access 11 to 14 : [11 12 13 14]
I want to access 30 to 21 : [30 29 28 27 26 25 24 23 22 21]
I want to access 30 to 21 : [30 29 28 27 26 25 24 23 22 21]
I want to access first row 5 to 10 and second row 20 to 25 :
[[ 5  6  7  8  9 10]
 [20 21 22 23 24 25]]


### **3D Array Slicing**

3D array me slicing ke liye:

**Syntax:**

array[matrix_slice, row_slice, column_slice]

**Example:**

arr = np.arange(1, 25).reshape(2, 3, 4)

print(arr)

Agar first matrix ke first two rows aur first three columns chahiye:

print(arr[0:1, 0:2, 0:3])

**Yahan:**

0:1 → Matrix selection

0:2 → Row selection

0:3 → Column selection

In [36]:
# 3-D slicing

a3 = np.arange(1, 101).reshape(2, 5, 10)
print(a3)

print()

# 1.Access element 88 using positive indexing. 
print(f"Access element 88 using positive indexing : {a3[1, 3, 7]}")

print()

# 2.Access element 43 using negative indexing. 
print(f"Access element 43 using negative indexing : {a3[-2, -1, -8]}")

print()

# 3.Access element 58 — write both positive and negative indexing. 
print(f"Access element 58 — write both positive : {a3[1, 0, 7]} and negative indexing : {a3[-1, -5, -3]}")


[[[  1   2   3   4   5   6   7   8   9  10]
  [ 11  12  13  14  15  16  17  18  19  20]
  [ 21  22  23  24  25  26  27  28  29  30]
  [ 31  32  33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48  49  50]]

 [[ 51  52  53  54  55  56  57  58  59  60]
  [ 61  62  63  64  65  66  67  68  69  70]
  [ 71  72  73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88  89  90]
  [ 91  92  93  94  95  96  97  98  99 100]]]

Access element 88 using positive indexing : 88

Access element 43 using negative indexing : 43

Access element 58 — write both positive : 58 and negative indexing : 58


In [37]:
# 4.Extract the entire Block 0 → 
print(f"Extract the entire Block 0 :")
print(a3[0])

print()

# 5. Extract the entire Block 1 → 
print(f"Extract the entire Block 1 :")
print(a3[1])

print()

# 6.Extract all first rows from both blocks → 
print(f"Extract all first rows from both blocks :")
print(a3[:, 0])

Extract the entire Block 0 :
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]

Extract the entire Block 1 :
[[ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

Extract all first rows from both blocks :
[[ 1  2  3  4  5  6  7  8  9 10]
 [51 52 53 54 55 56 57 58 59 60]]


In [38]:
# 7.Extract first 2 columns of Block 1 → 
print(f"Extract first 2 columns of Block 1 :")
print(a3[1, :, 0 : 2])

print()

# 8.Extract last 2 columns of Block 0 → 
print(f"Extract last 2 columns of Block 0 :")
print(a3[0, :, -2:])

print()

# 9.Extract element at Block 1, Row 0, last 2 columns.
print(f"Extract element at Block 1, Row 0, last 2 columns :")
print(a3[1, 0, -2 :])

Extract first 2 columns of Block 1 :
[[51 52]
 [61 62]
 [71 72]
 [81 82]
 [91 92]]

Extract last 2 columns of Block 0 :
[[ 9 10]
 [19 20]
 [29 30]
 [39 40]
 [49 50]]

Extract element at Block 1, Row 0, last 2 columns :
[59 60]


In [39]:
# 10.Reshape the array into shape (2, 2, 25) 
print(f"Reshape the array into shape (2, 2, 25) :") 
a3 = a3.reshape(2, 2, 25)
print(a3)

print()

# 11. Access element 25,75 using negative indexing. 
print(f"Access element 25,75 using negative indexing : {a3[:, -2, -1]}")

Reshape the array into shape (2, 2, 25) :
[[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
    18  19  20  21  22  23  24  25]
  [ 26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42
    43  44  45  46  47  48  49  50]]

 [[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
    68  69  70  71  72  73  74  75]
  [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
    93  94  95  96  97  98  99 100]]]

Access element 25,75 using negative indexing : [25 75]


### **Assignment**

In [40]:

#! 1D array [10, 20, 30, 40, 50] se 3rd index ki value extract karein.  
arr = np.array([10, 20, 30, 40, 50])
print(f"Access The 3rd Index of the Array : {arr[2]}")
 
#! Usi array se negative indexing use karke last element extract karein.
print(f"Access The Last Value of the Array : {arr[-1]}")

#! Array np.arange(10, 21) se values [12, 13, 14] slice karein. 
arr3 = np.arange(10, 21)
print(f"Access The values [12, 13, 14] in The Array : {arr3[2 : 5]}")

#! Array np.arange(10, 21) se aakhri 3 elements slice karein.  
print(f"Access The Last 3 values in The Array : {arr3[-3 : ]}")

#! Array [1, 2, 3, 4, 5, 6, 7, 8] ko reverse karein using step slicing [::-1].   
arr5 = np.arange(1, 9)
print(f"Access All The Value in Reverse Order : {arr5[::-1]}")

Access The 3rd Index of the Array : 30
Access The Last Value of the Array : 50
Access The values [12, 13, 14] in The Array : [12 13 14]
Access The Last 3 values in The Array : [18 19 20]
Access All The Value in Reverse Order : [8 7 6 5 4 3 2 1]


In [41]:

#! Array np.arange(1, 11) se har alternate element (step=2) select karein.   
arr6 = np.arange(1, 11, 2)
print(f"Even Array : {arr6}")

#! Ek 3x3 matrix banayein; uski Row 1, Column 2 ki value access karein using [r, c] syntax. 
arr7 = np.arange(1, 10).reshape(3, 3)
print(f"\n3 x 3 Matrix : \n{arr7}")
print(f"\nAccess the array's Row 1, Column 2 value : {arr7[0, 1]}")

#! Ek 3x4 matrix ki poori 2nd row extract karein.   
arr8 = np.arange(1, 13).reshape(3, 4)
print(f"\n3 x 4 Matrix : \n{arr8}")
print(f"\nAccess the complete 2nd row of the array : {arr8[1]}")

#! Ek 3x4 matrix ka poora 3rd column extract karein.  
print(f"\nAccess the complete 3rd column of the array : {arr8[:, 2]}")

#! Ek 4x4 matrix ke top-left ka 2x2 sub-matrix crop karein.   
arr10 = np.arange(1, 17).reshape(4, 4)
print(f"\n4 x 4 Matrix : \n{arr10}")
print(f"\nTop-left 2x2 Sub-matrix : \n{arr10[ : 2, : 2]}")

Even Array : [1 3 5 7 9]

3 x 3 Matrix : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Access the array's Row 1, Column 2 value : 2

3 x 4 Matrix : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Access the complete 2nd row of the array : [5 6 7 8]

Access the complete 3rd column of the array : [ 3  7 11]

4 x 4 Matrix : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Top-left 2x2 Sub-matrix : 
[[1 2]
 [5 6]]


In [47]:

#! Ek 4x4 matrix ke bottom-right ka 2x2 sub-matrix crop karein.   
print(f"\n4 x 4 Matrix : \n{arr10}")
print(f"\nbottom-right 2x2 Sub-matrix : \n{arr10[-2 : , -2 : ]}")

#! Ek 5x5 matrix se alternate rows aur alternate columns extract karein using [::2, ::2].
arr11 = np.arange(1, 26).reshape(5, 5)
print(f"\n5 x 5 Matrix : \n{arr11}")
print(f"Extract the alternate rows or alternate columns : \n{arr11[::2, ::2]}")

#! Diye gaye 2D matrix me Row 1 ke sabhi elements ko 0 assign karein (in-place modification).
print(f"\n2D Matrix : \n{arr10}")
arr10[0] = 0
print(f"\nAssign 0 in the 2D matrix row 1 value : \n{arr10}")

#! 3D array shape (2, 3, 3) se Block 0 ko poora extract karein.  
arr14 = np.arange(1, 19).reshape(2, 3, 3)
print(f"\n3D Array : \n{arr14}") 
print(f"\nExtract the Block 0 of the 3D Array : \n{arr14[0]}")

#! 3D array se Block 1, Row 2, Column 1 ka element access karein.   
print(f"\nAccess the Block 1, Row 2, Column 1's element of the 3D Array : \n{arr14[0, 1, 0]}")


4 x 4 Matrix : 
[[ 0  0  0  0]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

bottom-right 2x2 Sub-matrix : 
[[11 12]
 [15 16]]

5 x 5 Matrix : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Extract the alternate rows or alternate columns : 
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]

2D Matrix : 
[[ 0  0  0  0]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Assign 0 in the 2D matrix row 1 value : 
[[ 0  0  0  0]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

3D Array : 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]

Extract the Block 0 of the 3D Array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Access the Block 1, Row 2, Column 1's element of the 3D Array : 
4


In [54]:

#! 3D array ke dono blocks ki pehli rows ek sath extract karein using [:, 0, :].   
print(f"\nExtract both the Block 1 and 2, Row 1's element of the 3D Array : \n{arr14[ :, 0, :]}")

#! 3D array se dono blocks ke aakhri do columns extract karein using [:, :, -2:].  
print(f"\nExtract both the Block 1 and 2, last 2 columns element of the 3D Array : \n{arr14[ :, :, -2 : ]}")

#! Kisi 1D slice s = arr[1:4] ko modify karein aur check karein ki original array badla ya nahi (View check).   
print(f"\n1D Array : {arr}")
s = arr[1 : 4]
s *= 2
print(f"\nAfter modify the 'S' check 1D Array / Original Array automatically update or not : \n{arr}")

#! Matrix arr = np.arange(16).reshape(4, 4) se internal elements [[5, 6], [9, 10]] extract karein.
arr19 = np.arange(16).reshape(4, 4)
print(f"\n 2D Matrix : \n{arr19}")
print(f"\nExtract the row 2 and 3, column 2 and 3 : \n{arr19[1 : 3, 1 : 3]}")

#! Ek 1D array se reverse order me alternate elements slice karein using [::-2].
print(f"\n1D Array : {arr}")
print(f"\nExtract the array in reverse order with alternate elements : \n{arr[::-2]}")


Extract both the Block 1 and 2, Row 1's element of the 3D Array : 
[[ 1  2  3]
 [10 11 12]]

Extract both the Block 1 and 2, last 2 columns element of the 3D Array : 
[[[ 2  3]
  [ 5  6]
  [ 8  9]]

 [[11 12]
  [14 15]
  [17 18]]]

1D Array : [10 20 30 40 50]

After modify the 'S' check 1D Array / Original Array automatically update or not : 
[10 40 60 80 50]

 2D Matrix : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extract the row 2 and 3, column 2 and 3 : 
[[ 5  6]
 [ 9 10]]

1D Array : [10 40 60 80 50]

Extract the array in reverse order with alternate elements : 
[50 60 10]
