# **NumPy Shape & Dimension Manipulation**

Shape Manipulation ka matlab hai kisi array ke original elements ko mutate ya delete kiye bina uske structural dimensions (rows, columns, axes) ko modify karna.

### **AI/ML Relevance:**
* **Machine Learning (Scikit-Learn):** Algorithms 1D feature `(N,)` accept nahi karte; unhe 2D matrix `(N, features)` chahiye hota hai.
* **Deep Learning (PyTorch):** Models batch inputs format expect karte hain jaise `(Batch_Size, Channels, Height, Width)`.
* **Dimension Cleanup:** Predictions ke baad single unwanted dimensions (jaise `(1, 1, 5)`) ko clean karna padta hai.

**Examples:**

1D → (N,)

2D → (Rows, Columns)

3D → (Depth, Rows, Columns)

4D → (Batch, Channels, Height, Width)

Important: Shape change karte waqt array ke actual values generally same rehte hain; hum un values ko organize karne ka structure change karte hain.

### **1. Reshaping — reshape()**

reshape() ka use array ka shape change karne ke liye hota hai bina elements ki total quantity ko change kiye.

**Syntax**
arr.reshape(new_shape)

**Examples:**

arr.reshape(rows, columns)

#### **Golden Rule**

Original array ke total elements aur new shape ke total positions same hone chahiye.

**Mathematically:**

Original size = New shape ke dimensions ka product

**Example:**

12 elements

(3, 4)

3 × 4 = 12

(2, 2, 3)

2 × 2 × 3 = 12

(2, 6)

2 × 6 = 12

**Isliye ye valid shapes hain:**

(3, 4), (2, 6), (1, 12), (2, 2, 3)


**Lekin:**

(3, 5)

**invalid hai kyunki:**

3 × 5 = 15 ≠ 12

In [56]:
import numpy as np

arr = np.arange(1, 13)
print("Original 1D Array:\n", arr)
print(f"\nShape: {arr.shape} | Size: {arr.size}")

# Manual Reshape
mat_2d = arr.reshape(3, 4)
print("\nReshaped (3, 4):\n", mat_2d)

Original 1D Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Shape: (12,) | Size: 12

Reshaped (3, 4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### **The Auto-Dimension (-1)** 
Agar kisi ek dimension ki calculation manually nahi karni, toh wahan -1 pass kar sakte hain. NumPy total elements ke hisaab se use auto-calculate kar lega.   

**Formula:** $\text{Missing Dimension} = \frac{\text{Total Elements}}{\text{Product of Given Dimensions}}$

**Rule:** Ek reshape() call me sirf ek hi dimension -1 ho sakti hai.

**Example:**

arr = np.arange(12)

mat = arr.reshape(3, -1)

print(mat)

print(mat.shape)

**Output:**

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

(3, 4)

**Yahan:**

Total elements = 12

Given rows = 3

Columns = 12 ÷ 3

        = 4

**Isliye:**

reshape(3, -1)

**automatically:**

reshape(3, 4)

ban gaya.

#### **Important Rule**

Ek reshape() me sirf ek dimension ko -1 rakha ja sakta hai.

**Correct:**

arr.reshape(3, -1)

**Incorrect:**

arr.reshape(-1, -1)

In [57]:
# -1 Auto Calculation (Columns auto-calculated: 12 / 2 = 6)
auto_col = arr.reshape(2, -1)
print(f"\nAuto Cols Shape (2, -1): {auto_col.shape}")
print(auto_col)

# 3D Reshape with -1
tensor_3d = arr.reshape(2, 3, -1)
print(f"\n3D Tensor Shape (2, 3, -1): {tensor_3d.shape}")


Auto Cols Shape (2, -1): (2, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

3D Tensor Shape (2, 3, -1): (2, 3, 2)


### **2. Resize — `resize()`**

`resize()` function array ke physical structure aur total elements dono ko alter karta hai.

* **reshape() vs resize() ka main farq:**
  - `reshape()` me total elements ka exact match hona mandatory hai (product of dimensions must equal original size).
  - `np.resize()` me total elements ka match hona zaroori nahi hota. Yeh array ke shape ko forcefully change kar deta hai.

#### **Core Behavior Rules:**
1. **Target Shape Badi Hai (Size Expansion):** Agar nayi shape me original array se zyada elements ki jagah hai, toh NumPy initial elements ko cyclic order me **repeat** karta hai.
2. **Target Shape Choti Hai (Size Truncation):** Agar nayi shape me kam elements ki jagah hai, toh extra elements ko bina kisi warning ke **truncate (cut)** kar diya jata hai.

**Syntax:**
- Function Style: `np.resize(array, (new_rows, new_cols))`
- In-place Method: `array.resize((new_rows, new_cols), refcheck=False)`

> **Interview Note:** `np.resize()` naya independent array return karta hai, jabki `arr.resize()` array ko in-place modify karta hai.

In [58]:
base_arr = np.array([10, 20, 30, 40])
print("Original Base Array:\n", base_arr)

# Larger shape -> Elements repeat
resized_large = np.resize(base_arr, (2, 4))
print("\nnp.resize to (2, 4) [Data Repeats]:\n", resized_large)

# Smaller shape -> Elements truncate
resized_small = np.resize(base_arr, (2, 1))
print("\nnp.resize to (2, 1) [Data Truncates]:\n", resized_small)

Original Base Array:
 [10 20 30 40]

np.resize to (2, 4) [Data Repeats]:
 [[10 20 30 40]
 [10 20 30 40]]

np.resize to (2, 1) [Data Truncates]:
 [[10]
 [20]]


### **3. Flattening: `ravel()` vs `flatten()`**

Flattening ka matlab hai kisi bhi multi-dimensional array (2D matrix ya 3D tensor) ko single 1D flat line me collapse karna.

NumPy me 1D conversion ke do standard methods hote hain:

| Feature | `ravel()` | `flatten()` |
| :--- | :--- | :--- |
| **Return Type** | Memory **View** (Reference) | Memory **Copy** (Naya buffer) |
| **Memory Allocation** | Zero extra memory (Point karta hai existing data ko) | Nayi memory block allocate hoti hai |
| **Execution Speed** | Extremely fast ($O(1)$ constant time) | Slower ($O(N)$ data duplication time) |
| **Mutation Effect** | Output ko badaloge toh **original array change hoga** | Output ko badaloge toh **original array safe rahega** |
| **Primary Use-Case** | High-performance calculations aur memory saving | Safe data manipulation jahan raw data preserve karna ho |

**Syntax:**
- `array.ravel()`
- `array.flatten()`

#### **Base Check:**
- `arr.ravel().base is not None` $\implies$ Proves yeh ek View hai.
- `arr.flatten().base is None` $\implies$ Proves yeh ek independent Copy hai.

In [59]:
mat = np.array([[1, 2], [3, 4]])

# 1. ravel() -> View Verification
r = mat.ravel()
r[0] = 999
print("Original Matrix after modifying ravel():\n", mat)
print(f"Is ravel a View? {r.base is not None}")

# Reset Matrix
mat = np.array([[1, 2], [3, 4]])

# 2. flatten() -> Copy Verification
f = mat.flatten()
f[0] = 888
print("\nOriginal Matrix after modifying flatten():\n", mat)
print(f"Is flatten an independent Copy? {f.base is None}")

Original Matrix after modifying ravel():
 [[999   2]
 [  3   4]]
Is ravel a View? True

Original Matrix after modifying flatten():
 [[1 2]
 [3 4]]
Is flatten an independent Copy? True


### **4. Adding Dimensions — `np.newaxis` & `np.expand_dims()`**

Machine Learning models (Scikit-Learn estimators, linear models) 1D feature array `(N,)` ko input ke tor par accept nahi karte; unhe input hamesha 2D format `(Samples, Features)` yani `(N, 1)` me chahiye hota hai.

Nayi axis add karne ke do standard tarike hote hain:

---

#### **1. `np.newaxis` (Slice-based Insertion)**
Indexing brackets ke andar `np.newaxis` lagakar nayi dimension introduce ki jaati hai:
- **Column Vector banana:** `arr[:, np.newaxis]` $\implies$ Shape `(N,)` convert hoti hai `(N, 1)` me.
- **Row Vector banana:** `arr[np.newaxis, :]` $\implies$ Shape `(N,)` convert hoti hai `(1, N)` me.

---

#### **2. `np.expand_dims()` (Function-based Insertion)**
Ek explicit axis parameter ke through nayi dimension insert karta hai:
- **Syntax:** `np.expand_dims(array, axis=X)`
  - `axis=0` $\implies$ Output shape: `(1, N)` (Batch dimension shuru me judta hai).
  - `axis=1` $\implies$ Output shape: `(N, 1)` (Feature dimension aakhir me judta hai).
  - `axis=-1` $\implies$ Output array ke aakhri position par dimension add karta hai.

In [60]:
features = np.array([2.4, 3.1, 5.8, 7.2])  # Shape: (4,)
print(f"Original Feature Vector: {features.shape}")

# Column Vector for ML Input
col_vec_1 = features[:, np.newaxis]
col_vec_2 = np.expand_dims(features, axis=1)
print(f"Column Vector Shape using np.newaxis: {col_vec_1.shape}")
print(f"Column Vector Shape using np.expand_dims: {col_vec_2.shape}")

# Row Vector / Batch of 1 sample
row_vec = np.expand_dims(features, axis=0)
print(f"Row Vector Shape (Batch size 1): {row_vec.shape}")

Original Feature Vector: (4,)
Column Vector Shape using np.newaxis: (4, 1)
Column Vector Shape using np.expand_dims: (4, 1)
Row Vector Shape (Batch size 1): (1, 4)


### **5. Removing Single Dimensions — `np.squeeze()`**

Neural network layers aur deep learning models prediction return karte waqt output shape me faaltu single-dimensional axes (jahan dimension size `1` ho) chhod dete hain.

* **Problem Scenario:** Binary classification ya single sample prediction ka output aksar `(1, 1, 3)` ya `(1, 10)` shape me aata hai.
* **Solution:** `np.squeeze()` array me se un sabhi axes ko drop kar deta hai jinki length exact `1` hoti hai, bina actual elements ko alter kiye.

**Example Shape Flow:**
$$\text{Raw Model Output: } (1, 1, 5) \xrightarrow{\text{np.squeeze()}} (5,)$$

**Syntax:**
- Pure array se saare `1` drop karna: `np.squeeze(array)`
- Kisi specific axis se `1` drop karna: `np.squeeze(array, axis=0)`

In [61]:
# Simulated Deep Learning model output: (Batch=1, Channel=1, Classes=3)
model_pred = np.array([[[0.15, 0.80, 0.05]]])
print(f"Raw Output Shape: {model_pred.shape}")

# Squeezing redundant axes
clean_pred = np.squeeze(model_pred)
print(f"Cleaned Output Shape: {clean_pred.shape}")
print("Probabilities:", clean_pred)

Raw Output Shape: (1, 1, 3)
Cleaned Output Shape: (3,)
Probabilities: [0.15 0.8  0.05]


### **6. Transpose & Axes Swapping — `.T`, `transpose()`, `swapaxes()`**

Tensors aur matrices ke axes ka orientation switch ya reverse karne ke liye yeh methods use hote hain:

---

#### **1. `.T` (2D Matrix Transposition)**
Rows aur columns ko aapas me swap karta hai:
- Row $i$, Column $j$ ban jata hai Row $j$, Column $i$.
- Shape `(M, N)` transpose ho kar `(N, M)` ban jaati hai.
- **Syntax:** `matrix.T`

---

#### **2. `np.transpose()` (Multi-Axis Permutation)**
Higher-dimensional tensors (3D+) ke axes sequence ko apni marzi se rearrange karne ke liye use hota hai.
- **Syntax:** `np.transpose(array, axes=(dim0, dim1, dim2))`
- **Computer Vision Pipeline Use-Case:**
  - PyTorch standard tensor format: `(Channels, Height, Width)` yani `(0, 1, 2)`.
  - Matplotlib image display format: `(Height, Width, Channels)`.
  - **Transformation:** `np.transpose(img_tensor, (1, 2, 0))`

---

#### **3. `np.swapaxes()` (Pairwise Axis Swap)**
Pure axis permutation likhne ke bajaye sirf do specific axes ko aapas me interchange karta hai.
- **Syntax:** `np.swapaxes(array, axis1, axis2)`
- **Example:** Shape `(3, 32, 64)` par `np.swapaxes(arr, 0, 2)` lagane par shape `(64, 32, 3)` ban jaati hai.

In [62]:
# 1. 2D Transpose (.T)
mat = np.array([[1, 2, 3], [4, 5, 6]])
print("Original 2D (2, 3):\n", mat)
print("Transposed (3, 2):\n", mat.T)

# 2. Tensor Transposition (PyTorch Image Conversion)
# Shape: (Channels=3, Height=32, Width=32)
pytorch_tensor = np.random.randint(0, 256, (3, 32, 32))
print(f"\nPyTorch Tensor Format (C, H, W): {pytorch_tensor.shape}")

# Target: (Height=32, Width=32, Channels=3) -> Axis mapping: (1, 2, 0)
display_img = np.transpose(pytorch_tensor, (1, 2, 0))
print(f"Matplotlib Format (H, W, C): {display_img.shape}")

# 3. swapaxes (Interchanging Channel and Width directly)
swapped = np.swapaxes(pytorch_tensor, 0, 2)
print(f"Swapped Axes 0 & 2 Shape (W, H, C): {swapped.shape}")

Original 2D (2, 3):
 [[1 2 3]
 [4 5 6]]
Transposed (3, 2):
 [[1 4]
 [2 5]
 [3 6]]

PyTorch Tensor Format (C, H, W): (3, 32, 32)
Matplotlib Format (H, W, C): (32, 32, 3)
Swapped Axes 0 & 2 Shape (W, H, C): (32, 32, 3)


### **Assignment**

In [63]:

#! 1D array of 12 elements ko (3, 4) matrix me reshape karein. 
ar1 = np.arange(1, 13).reshape(3, 4)
print(f"\n1D Array reshaped to (3, 4) : \n{ar1}")

#! 1D array of 12 elements ko 3D array (2, 2, 3) me reshape karein.  
ar2 = np.arange(1, 13).reshape(2, 2, 3)
print(f"\n1D Array reshaped to 3D (2, 2, 3) : \n{ar2}") 

#! Shape (12,) ke array ko 4 rows me reshape karein using -1 auto-dimension trick.   
ar3 = np.arange(1, 13).reshape(-1, 4)
print(f"\n1D Array reshaped to (-1, 4) : \n{ar3}")

#! Shape (16,) ke array ko 2 columns me reshape karein using -1 for rows.   
ar4 = np.arange(1, 17).reshape(-1, 2)
print(f"\n1D Array reshaped to (-1, 2) : \n{ar4}")

#! Ek (2, 3) matrix ko 1D me convert karein using .ravel() aur uska .base check karein.   
ar5 = np.arange(1, 7).reshape(2, 3)
ravel_arr = ar5.ravel()
print(f"\nOriginal (2, 3) Matrix : \n{ar5}")
print(f"\nRaveled 1D Array : \n{ravel_arr}")
print(f"\nBase of Raveled Array : \n{ravel_arr.base}")


1D Array reshaped to (3, 4) : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1D Array reshaped to 3D (2, 2, 3) : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

1D Array reshaped to (-1, 4) : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1D Array reshaped to (-1, 2) : 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]

Original (2, 3) Matrix : 
[[1 2 3]
 [4 5 6]]

Raveled 1D Array : 
[1 2 3 4 5 6]

Base of Raveled Array : 
[1 2 3 4 5 6]


In [64]:

#! Ek (2, 3) matrix ko 1D me convert karein using .flatten() aur verify karein ki yeh copy hai.  
flatten_arr = ar5.flatten()
print(f"\nOriginal (2, 3) Matrix : \n{ar5}")
print(f"\nFlattened 1D Array : \n{flatten_arr}")

#! ravel() ke ek element ko update karein aur verify karein ki original matrix par kya asar hua. 
ravel_arr[0] = 999
print(f"\nUpdated Raveled Array : \n{ravel_arr}")
print(f"\nOriginal Matrix after ravel() update : \n{ar5}")

#! flatten() ke ek element ko update karein aur verify karein ki original matrix safe hai ya nahi.   
flatten_arr[0] = 888
print(f"\nUpdated Flattened Array : \n{flatten_arr}")
print(f"\nOriginal Matrix after flatten() update : \n{ar5}")

#! Array [1, 2, 3] ko np.resize() se (2, 4) shape me resize karein aur repeating pattern dekhein.   
ar9 = np.array([1, 2, 3])
resized_repeat = np.resize(ar9, (2, 4))
print(f"\nResized Array with Repetition : \n{resized_repeat}")

#! Array np.arange(10) ko np.resize() se (2, 3) me resize karke data truncation dekhein.   
ar10 = np.arange(10)
resized_truncate = np.resize(ar10, (2, 3))
print(f"\nResized Array with Truncation : \n{resized_truncate}")



Original (2, 3) Matrix : 
[[1 2 3]
 [4 5 6]]

Flattened 1D Array : 
[1 2 3 4 5 6]

Updated Raveled Array : 
[999   2   3   4   5   6]

Original Matrix after ravel() update : 
[[999   2   3]
 [  4   5   6]]

Updated Flattened Array : 
[888   2   3   4   5   6]

Original Matrix after flatten() update : 
[[999   2   3]
 [  4   5   6]]

Resized Array with Repetition : 
[[1 2 3 1]
 [2 3 1 2]]

Resized Array with Truncation : 
[[0 1 2]
 [3 4 5]]


In [65]:

#! 1D array (5,) ko Column Vector (5, 1) me badlein using np.newaxis. 
ar11 = np.arange(1, 6) 
new_ar11 = ar11[ : , np.newaxis]
print(f"Give Newaxis Array (5,) into : {new_ar11.shape}")
  
#! 1D array (5,) ko Row Vector (1, 5) me badlein using np.newaxis.   
new_ar12 = ar11[np.newaxis, : ]
print(f"\nGive Newaxis Array (5,) into : {new_ar12.shape}")

#! 1D array (4,) par np.expand_dims() lagakar shape (1, 4) banayein. 
exp_ar13 = np.expand_dims(ar11, axis = 0) 
print(f"\nExpand the dimension of the array (4,) into : {exp_ar13}")
  
#! 1D array (4,) par np.expand_dims() lagakar shape (4, 1) banayein.  
exp_ar14 = np.expand_dims(ar11, axis = 1) 
print(f"\nExpand the dimension of the array (4,) into : {exp_ar13}")

#! Array shape (1, 1, 5) par np.squeeze() lagakar uski redundant axes drop karein.   
ar15 = np.arange(1, 6).reshape(1, 1, 5)
sq_ar15 = np.squeeze(ar15)
print(f"\nRedundant array axes (1, 1, 5) into : {sq_ar15.shape}")

Give Newaxis Array (5,) into : (5, 1)

Give Newaxis Array (5,) into : (1, 5)

Expand the dimension of the array (4,) into : [[1 2 3 4 5]]

Expand the dimension of the array (4,) into : [[1 2 3 4 5]]

Redundant array axes (1, 1, 5) into : (5,)


In [66]:

#! Array shape (1, 3, 1) me se sirf specific axis=0 ko squeeze karein.
ar16 = np.arange(1, 4).reshape(1, 3, 1)
sq_ar16 = np.squeeze(ar16, axis = 0)
print(f"\nRedundant array axes (1, 3, 1) into : {sq_ar16.shape}")

#! Ek (2, 5) matrix ka transpose nikaalein using .T.  
ar17 = np.arange(1, 11).reshape(2, 5)
t_ar17 = ar17.T
print(f"\nOriginal Array : \n{ar17}")
print(f"\nTranspose Array : \n{t_ar17}")

#! Ek (3, 4) matrix ka transpose nikaalein using np.transpose().   
ar18 = np.arange(1, 13).reshape(3, 4)
t_ar18 = np.transpose(ar18)
print(f"\nOriginal Array : \n{ar18}")
print(f"\nTranspose Array : \n{t_ar18}")


Redundant array axes (1, 3, 1) into : (3, 1)

Original Array : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Transpose Array : 
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]

Original Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transpose Array : 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [67]:

#! 3D tensor shape (2, 3, 4) me axis 0 aur axis 2 ko aapas me interchange karein using np.swapaxes().   
ar19 = np.arange(1, 25).reshape(2, 3, 4)
swap_ar19 = np.swapaxes(ar19, 0, 2)
print(f"\nOriginal Array : \n{ar19}")
print(f"\nSwapped Array : \n{swap_ar19}")


Original Array : 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Swapped Array : 
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]


In [68]:

#! 3D tensor shape (3, 32, 64) ke sabhi axes ko order (1, 2, 0) me transpose karein.   
ar20 = np.random.randint(0, 256, (3, 32, 64))
t_ar20 = np.transpose(ar20, (1, 2, 0))
print(f"\nOriginal Array : \n{ar20}")
print(f"\nTransposed Array : \n{t_ar20}")


Original Array : 
[[[200 171 189 ...  20  67  80]
  [114 227 225 ...  76  24  81]
  [ 21 138 157 ... 202 239  83]
  ...
  [184 142  16 ... 243  33  74]
  [133 135  27 ... 189 187  39]
  [225 160 203 ... 232  77  21]]

 [[120  17 194 ...  46   5   5]
  [248  35 249 ... 116  95 166]
  [ 83 142  19 ... 234  29  92]
  ...
  [174 191 184 ...  22 209  59]
  [175 177  89 ... 249 205 252]
  [201 199 226 ... 210  32  22]]

 [[213  25  29 ... 136 187   3]
  [229  45   3 ... 103  39 110]
  [122  12 221 ... 233  56   1]
  ...
  [ 88  75 200 ...  43 141 163]
  [111  91 189 ...  29 116 218]
  [ 35  19 149 ...  42 141 150]]]

Transposed Array : 
[[[200 120 213]
  [171  17  25]
  [189 194  29]
  ...
  [ 20  46 136]
  [ 67   5 187]
  [ 80   5   3]]

 [[114 248 229]
  [227  35  45]
  [225 249   3]
  ...
  [ 76 116 103]
  [ 24  95  39]
  [ 81 166 110]]

 [[ 21  83 122]
  [138 142  12]
  [157  19 221]
  ...
  [202 234 233]
  [239  29  56]
  [ 83  92   1]]

 ...

 [[184 174  88]
  [142 191  75]
  [ 16 184