# **NumPy Phase 4: Joining, Splitting & Array Mutation**

Is phase me hum seekhenge ki alag-alag arrays ko aapas me kaise jodte hain (Joining), bade array ke tukde kaise karte hain (Splitting), aur array me naye elements add ya delete kaise karte hain (Mutation).

---

### **1. Joining Arrays: `concatenate()` vs `stack()`**

Do ya zyada arrays ko aapas me jodna:

* **`np.concatenate()`:** Existing dimension ke along arrays ko jodta hai (Naya bracket ya dimension add **nahi** hota).
  * `axis=0` $\implies$ Row-wise jodna (Vertical join).
  * `axis=1` $\implies$ Column-wise jodna (Horizontal join).

* **`np.stack()`:** Arrays ko jodte waqt ek **naya dimension (bracket)** create karta hai (e.g., do 1D arrays milkar 2D matrix ban jaate hain).

* **Shortcuts:**
  * **`np.vstack()` (Vertical Stack):** Rows ke roop me ek ke niche ek jodta hai (`axis=0`).
  * **`np.hstack()` (Horizontal Stack):** Columns ke roop me barabar me jodta hai (`axis=1`).

In [2]:
import numpy as np

# Base Arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Array a:", a)
print("Array b:", b)

# 1. concatenate (Result remains 1D)
concat_arr = np.concatenate((a, b))
print("\nconcatenate (1D):", concat_arr)
print("Shape:", concat_arr.shape)

# 2. stack (Creates a new 2D array)
stacked_arr = np.stack((a, b), axis=0)
print("\nstack axis=0 (Creates 2D):\n", stacked_arr)
print("Shape:", stacked_arr.shape)

# 3. vstack & hstack
print("\nvstack (Rows ke roop me):\n", np.vstack((a, b)))
print("\nhstack (Single line columns):\n", np.hstack((a, b)))

Array a: [1 2 3]
Array b: [4 5 6]

concatenate (1D): [1 2 3 4 5 6]
Shape: (6,)

stack axis=0 (Creates 2D):
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

vstack (Rows ke roop me):
 [[1 2 3]
 [4 5 6]]

hstack (Single line columns):
 [1 2 3 4 5 6]


### **2. Splitting Arrays: `split()`, `hsplit()`, `vsplit()`**

Ek array ko do ya usse zyada barabar hisson me divide karna:

* **`np.split(array, parts, axis)`:** Specified axis par array ke barabar tukde karta hai.
* **`np.vsplit(array, parts)`:** Matrix ko rows ke hisaab se beech me se kat-ta hai (Vertical split).
* **`np.hsplit(array, parts)`:** Matrix ko columns ke hisaab se alag karta hai (Horizontal split).

In [3]:
# 1D Splitting
arr_1d = np.arange(1, 7)  # [1, 2, 3, 4, 5, 6]
parts = np.split(arr_1d, 3)  # 3 equal parts of 2 elements each
print("1D split into 3 parts:")
for p in parts:
    print(p)

print()

# 2D Splitting (Matrix of 4x4)
mat = np.arange(16).reshape(4, 4)
print("Original 4x4 Matrix:\n", mat)

# vsplit (Row-wise cut: 2 matrices of 2x4)
top, bottom = np.vsplit(mat, 2)
print("\nvsplit (Top Half):\n", top)
print("\nvsplit (Bottom Half):\n", bottom)

# hsplit (Column-wise cut: 2 matrices of 4x2)
left, right = np.hsplit(mat, 2)
print("\nhsplit (Left Half):\n", left)
print("\nhsplit (Right Half):\n", right)

1D split into 3 parts:
[1 2]
[3 4]
[5 6]

Original 4x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

vsplit (Top Half):
 [[0 1 2 3]
 [4 5 6 7]]

vsplit (Bottom Half):
 [[ 8  9 10 11]
 [12 13 14 15]]

hsplit (Left Half):
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

hsplit (Right Half):
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### **3. Array Mutation: `append()`, `insert()`, `delete()`**

NumPy array me naye elements jodne ya purane elements hatane ke liye:

* **`np.append(array, values)`:** Array ke aakhri (end) me nayi values jodta hai.
* **`np.insert(array, index, values)`:** Kisi specific index par element insert karta hai.
* **`np.delete(array, index)`:** Kisi specific index ke element ya poori row/column ko delete karta hai.

> **Important Note:** NumPy array ka memory size fixed hota hai. Isliye jab bhi hum `append` ya `insert` karte hain, NumPy internally ek **naya array** banakar return karta hai.

In [4]:
x = np.array([10, 20, 30, 40, 50])
print("Original array:", x)

# 1. append
appended = np.append(x, [60, 70])
print("\nAfter np.append:", appended)

# 2. insert (Index 2 par 99 add karna)
inserted = np.insert(x, 2, 99)
print("\nAfter np.insert at index 2:", inserted)

# 3. delete (Index 1 ki value 20 delete karna)
deleted = np.delete(x, 1)
print("\nAfter np.delete index 1:", deleted)

# 2D Matrix row/column delete
grid = np.array([[1, 2], [3, 4], [5, 6]])
print("\nOriginal 2D Grid:\n", grid)

# Row delete (axis=0) -> Delete row index 1
grid_no_row = np.delete(grid, 1, axis=0)
print("\nGrid after deleting Row 1 (axis=0):\n", grid_no_row)

Original array: [10 20 30 40 50]

After np.append: [10 20 30 40 50 60 70]

After np.insert at index 2: [10 20 99 30 40 50]

After np.delete index 1: [10 30 40 50]

Original 2D Grid:
 [[1 2]
 [3 4]
 [5 6]]

Grid after deleting Row 1 (axis=0):
 [[1 2]
 [5 6]]


### **4. Advanced Array Mutation & Replacement Operations**

Jab array ke shape ko delete kiye bina sirf uske andar ki values ko modify ya transform karna ho:

---

#### **1. `np.clip()` (Values ko Limit / Cap karna)**
Kisi array ki values ko ek minimum aur maximum boundary ke andar lock kar deta hai.
* Agar koi value `min` se choti hai $\to$ Use `min` bana deta hai.
* Agar koi value `max` se badi hai $\to$ Use `max` bana deta hai.
* **Use-Case:** Outliers ko trim karna ya pixel values ko 0 se 255 ke beech clamp karna.

**Syntax:** `np.clip(array, min_value, max_value)`

---

#### **2. `np.repeat()` vs `np.tile()` (Elements ko Multiply karna)**
* **`np.repeat(arr, repeats)`:** Array ke har ek individual element ko baar-baar repeat karta hai (e.g., `[1, 2]` $\to$ `[1, 1, 2, 2]`).
* **`np.tile(arr, reps)`:** Poore array ke block ko ek saath repeat karta hai (e.g., `[1, 2]` $\to$ `[1, 2, 1, 2]`).

---

#### **3. `np.unique()` (Duplicates hatana & Frequency nikalna)**
Array me se repeated values hata kar unique sorted values deta hai aur unka count bhi return kar sakta hai.

**Syntax:** `np.unique(array, return_counts=True)`

In [5]:
# 1. np.clip (Outlier Capping)
raw_scores = np.array([-15, 20, 55, 90, 140, 200])
print("Original Scores:", raw_scores)

# Values ko 0 aur 100 ke beech cap karna
clean_scores = np.clip(raw_scores, 0, 100)
print("Clipped Scores (0 to 100):", clean_scores)

print()

# 2. np.repeat vs np.tile
sample = np.array([1, 2, 3])
print("Original Sample:", sample)

# Element-wise repeat
print("np.repeat (har number 3 baar):", np.repeat(sample, 3))

# Full pattern tile
print("np.tile (poora pattern 3 baar):", np.tile(sample, 3))

print()

# 3. np.unique (Duplicates & Counts)
data = np.array([5, 2, 8, 2, 5, 5, 9, 8])
unique_vals, counts = np.unique(data, return_counts=True)

print("Original Array with Duplicates:", data)
print("Unique Elements:", unique_vals)
print("Har Element ka Count:", counts)

Original Scores: [-15  20  55  90 140 200]
Clipped Scores (0 to 100): [  0  20  55  90 100 100]

Original Sample: [1 2 3]
np.repeat (har number 3 baar): [1 1 1 2 2 2 3 3 3]
np.tile (poora pattern 3 baar): [1 2 3 1 2 3 1 2 3]

Original Array with Duplicates: [5 2 8 2 5 5 9 8]
Unique Elements: [2 5 8 9]
Har Element ka Count: [2 3 2 1]


### **Assignment**

In [14]:

#! Do 1D arrays [1, 2] aur [3, 4] ko np.concatenate() se horizontally jodein.   
ar0 = np.array([1, 2])
ar1 = np.array([3, 4])
concatenated = np.concatenate((ar0, ar1))
print("\nConcatenated 1D Arrays:", concatenated)

#! Do 2D matrices (2, 3) ko vertical row-wise jodein using np.concatenate(axis=0).  
ar2 = np.arange(1, 7).reshape(2, 3)
ar_2 = np.arange(11, 17).reshape(2, 3)
concatenated_ar2 = np.concatenate((ar2, ar_2), axis = 0)
print(f"\nConcatenated 2D Arrays:\n", concatenated_ar2)

#! Do 2D matrices (2, 3) ko horizontal column-wise jodein using np.concatenate(axis=1).   
concatenated_ar3 = np.concatenate((ar2, ar_2), axis = 1)
print(f"\nConcatenated 2D Arrays:\n", concatenated_ar3)

#! Do 1D arrays [1, 2, 3] aur [4, 5, 6] ko np.stack(axis=0) se jodkar (2, 3) matrix banayein.   
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
stack_ar = np.stack((a1, a2), axis = 0)
print(f"\n1D Arrays Convert into 2D Array Using Stack :\n", stack_ar)

#! Unhi do 1D arrays ko np.stack(axis=1) se jodkar (3, 2) matrix banayein.   
stack_ar2 = np.stack((a1, a2), axis = 1)
print(f"\n1D Arrays Convert into 2D Array Using Stack :\n", stack_ar2)


Concatenated 1D Arrays: [1 2 3 4]

Concatenated 2D Arrays:
 [[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]

Concatenated 2D Arrays:
 [[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]

1D Arrays Convert into 2D Array Using Stack :
 [[1 2 3]
 [4 5 6]]

1D Arrays Convert into 2D Array Using Stack :
 [[1 4]
 [2 5]
 [3 6]]


In [23]:

#! Do 1D arrays ko vertical stack karein using np.vstack().   
stack_ar3 = np.vstack((a1, a2))
print(f"\n1D Arrays Convert into 2D Array Using Stack :\n", stack_ar3)

#! Do 1D arrays ko horizontal stack karein using np.hstack().   
stack_ar4 = np.hstack((a1, a2))
print(f"\n1D Arrays Convert into 2D Array Using Stack :\n", stack_ar4)

#! Array np.arange(10) ko 2 barabar hisson me divide karein using np.split().  
ar8 = np.arange(10)
split_ar = np.split(ar8, 2)
print(f"\nOriginal Array : {ar8}")
print(f"\nSplit 1D Array into 2 Equal Part Using Split : \n{split_ar}")

#! Array np.arange(12) ko 4 barabar hisson me divide karein using np.split().  
ar9 = np.arange(12)
split_ar2 = np.split(ar9, 4)
print(f"\nOriginal Array : {ar9}")
print(f"\nSplit 1D Array into 4 Equal Part Using Split : \n{split_ar2}")

#! Ek 4x4 matrix ko row-wise 2 matrices me cut karein using np.vsplit().   
ar10 = np.arange(16).reshape(4, 4)
split_ar3 = np.vsplit(ar10, 2)
print(f"\nOriginal Array : \n{ar10}")
print(f"\nSplit 4 x 4 Matrix into 2 Row-Wise Equal Matrix Using Vsplit : \n{split_ar3}")


1D Arrays Convert into 2D Array Using Stack :
 [[1 2 3]
 [4 5 6]]

1D Arrays Convert into 2D Array Using Stack :
 [1 2 3 4 5 6]

Original Array : [0 1 2 3 4 5 6 7 8 9]

Split 1D Array into 2 Equal Part Using Split : 
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

Original Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

Split 1D Array into 4 Equal Part Using Split : 
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

Original Array : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Split 4 x 4 Matrix into 2 Row-Wise Equal Matrix Using Vsplit : 
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [34]:

#! Ek 4x4 matrix ko column-wise 2 matrices me cut karein using np.hsplit().  
split_ar4 = np.hsplit(ar10, 2)
print(f"\nOriginal Array : \n{ar10}")
print(f"\nSplit 4 x 4 Matrix into 2 Column-Wise Equal Matrix Using Vsplit : \n{split_ar4}")

#! 1D array ke end me elements [50, 60] jodien using np.append().   
print(f"\nOriginal Array : {ar0}")
ap_ar = np.append(ar0, [50, 60])
print(f"\nAt The End Of The Array Add The Element Using Append : {ap_ar}")

#! Ek 2x2 matrix ke end me ek nayi row append karein using np.append(..., axis=0).
print(f"\nOriginal Array : \n{ar10}")
ap_ar2 = np.append(ar10, [[21, 22, 23, 24]], axis=0)
print(f"\nAt The End Of The 2 x 2 Matrix Add The New Row Using Append : {ap_ar2}")

#! 1D array ke index 2 par value 99 add karein using np.insert(). 
print(f"\nOriginal Array : {ar0}")
in_ar = np.insert(ar0, 2, 99) 
print(f"\nAfter Inserting Value 99 At Index 2 : {in_ar}")

#! Ek 3x3 matrix me index 1 par ek nayi row insert karein using np.insert(..., axis=0).
ar15 = np.arange(9).reshape(3, 3)
print(f"\nOriginal 3 x 3 Matrix : \n{ar15}")
in_ar2 = np.insert(ar15, 1, [[99, 98, 97]], axis = 0)
print(f"\nAfter Inserting New Row At Index 1 : \n{in_ar2}")


Original Array : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Split 4 x 4 Matrix into 2 Column-Wise Equal Matrix Using Vsplit : 
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]

Original Array : [1 2]

At The End Of The Array Add The Element Using Append : [ 1  2 50 60]

Original Array : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

At The End Of The 2 x 2 Matrix Add The New Row Using Append : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [21 22 23 24]]

Original Array : [1 2]

After Inserting Value 99 At Index 2 : [ 1  2 99]

Original 3 x 3 Matrix : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

After Inserting New Row At Index 1 : 
[[ 0  1  2]
 [99 98 97]
 [ 3  4  5]
 [ 6  7  8]]


In [40]:

#! 1D array se index 3 ki value delete karein using np.delete(). 
print(f"\nOriginal Array : {stack_ar4}")
del_ar = np.delete(stack_ar4, 3)
print(f"\nAfter Deleting Element At Index 3 : {del_ar}")

#! Ek 3x3 matrix se poori Row 1 delete karein using np.delete(..., axis=0).   
print(f"\nOriginal 3 x 3 Matrix : \n{ar15}")
del_ar2 = np.delete(ar15, 1, axis = 0)
print(f"\nAfter Deleting Row 1 : \n{del_ar2}")

#! Array [-10, 5, 20, 150] ki values ko 0 aur 100 ke beech limit/clamp karein using np.clip().
ar18 = np.array([-10, 5, 20, 150])
print(f"\nOriginal Array : {ar18}")
clipped_ar = np.clip(ar18, 0, 100)
print(f"\nAfter Clipping Values Between 0 and 100 : {clipped_ar}")

#! Array [1, 2, 3] ke har individual element ko 3 baar repeat karein using np.repeat() ([1, 1, 1, 2, ...]).
ar19 = np.array([1, 2, 3])
rep_ar = np.repeat(ar19, 3)
print(f"\nOriginal Array : {ar19}")
print(f"\nAfter Repeating Elements 3 Times : {rep_ar}")

#! Array [1, 2, 3] ke poore pattern ko 3 baar tile karein using np.tile() ([1, 2, 3, 1, 2, 3, ...]).
tile_ar = np.tile(ar19, 3)
print(f"\nOriginal Array : {ar19}")
print(f"\nAfter Tiling The Whole Pattern 3 Times : {tile_ar}")


Original Array : [1 2 3 4 5 6]

After Deleting Element At Index 3 : [1 2 3 5 6]

Original 3 x 3 Matrix : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

After Deleting Row 1 : 
[[0 1 2]
 [6 7 8]]

Original Array : [-10   5  20 150]

After Clipping Values Between 0 and 100 : [  0   5  20 100]

Original Array : [1 2 3]

After Repeating Elements 3 Times : [1 1 1 2 2 2 3 3 3]

Original Array : [1 2 3]

After Tiling The Whole Pattern 3 Times : [1 2 3 1 2 3 1 2 3]
