# **Vectorization, Operators & Broadcasting**

NumPy me calculations ke liye Python ki tarah `for` loops likhne ki zaroorat nahi padti. NumPy saare operations poore array par ek saath parallel execute karta hai, jise **Vectorization** kehte hain.

---

### **1. Basic Arithmetic Operators**

NumPy me har arithmetic operator **Element-wise** kaam karta hai (yani index `0` ka calculation index `0` ke sath, `1` ka `1` ke sath).

* `+` : Addition (`np.add`)
* `-` : Subtraction (`np.subtract`)
* `*` : Multiplication (`np.multiply`)
* `/` : Float Division (`np.divide`)
* `//` : Floor Division (Integer answer)
* `%` : Modulo (Remainder / Sheshphal)
* `**` : Exponentiation (Power)

In [42]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Array a:", a)
print("Array b:", b)

print("\n--- Arithmetic Operations ---")
print("Addition (a + b):", a + b)
print("Subtraction (a - b):", a - b)
print("Multiplication (a * b):", a * b)
print("Division (a / b):", a / b)
print("Floor Division (a // b):", a // b)
print("Modulo / Remainder (a % b):", a % b)
print("Power / Exponent (b ** 2):", b ** 2)

Array a: [10 20 30 40]
Array b: [2 4 5 8]

--- Arithmetic Operations ---
Addition (a + b): [12 24 35 48]
Subtraction (a - b): [ 8 16 25 32]
Multiplication (a * b): [ 20  80 150 320]
Division (a / b): [5. 5. 6. 5.]
Floor Division (a // b): [5 5 6 5]
Modulo / Remainder (a % b): [0 0 0 0]
Power / Exponent (b ** 2): [ 4 16 25 64]


### **2. Comparison & Logical Operators (Filtering)**

Yeh operators numbers ke bajaye `True` ya `False` (Boolean array) return karte hain.

* **Comparison Operators:** `>`, `<`, `>=`, `<=`, `==`, `!=`
* **Logical Operators:**
  * `&` (AND) : Dono conditions sach honi chahiye.
  * `|` (OR) : Dono me se koi ek condition sach honi chahiye.
  * `~` (NOT) : Condition ko invert (ulta) kar deta hai.

> **Important:** NumPy arrays ke sath Python ke `and`, `or`, `not` keywords kaam nahi karte; unki jagah bitwise symbols `&`, `|`, `~` use hote hain.

In [43]:
scores = np.array([35, 78, 92, 44, 60, 88])
print("Scores:", scores)

# Comparison Operator
print("\nScores >= 60 (Pass/Fail):", scores >= 60)

# Logical Operator: Scores between 50 AND 80
filter_condition = (scores >= 50) & (scores <= 80)
print("Scores between 50 and 80 (Boolean Mask):", filter_condition)

# Boolean Indexing: Actual passing numbers nikalna
print("Filtered Passing Scores:", scores[scores >= 60])

Scores: [35 78 92 44 60 88]

Scores >= 60 (Pass/Fail): [False  True  True False  True  True]
Scores between 50 and 80 (Boolean Mask): [False  True False False  True False]
Filtered Passing Scores: [78 92 60 88]


### **3. Universal Mathematical Functions (ufuncs)**

NumPy me common mathematical calculations ke liye built-in optimized functions hote hain:

* `np.sqrt(arr)` : Square root nikalna.
* `np.abs(arr)` : Negative values ko positive banana (Absolute value).
* `np.exp(arr)` : Exponential ($e^x$) calculate karna.
* `np.log(arr)` : Natural logarithm ($\ln$) calculate karna.

In [44]:
vals = np.array([1, 4, 9, 16, -25])
print("Original Values:", vals)

# Square root (positive numbers par)
print("Square Root (1, 4, 9, 16):", np.sqrt(vals[:4]))

# Absolute value
print("Absolute values (negative to positive):", np.abs(vals))

Original Values: [  1   4   9  16 -25]
Square Root (1, 4, 9, 16): [1. 2. 3. 4.]
Absolute values (negative to positive): [ 1  4  9 16 25]


### **4. Broadcasting Rules**

**Broadcasting** ka matlab hota hai: Jab do alag-alag shape ke arrays par calculation karni ho, toh NumPy automatically chote array ko stretch karke bade array ke barabar fit kar deta hai[cite: 1].

---

#### **Rule 1: Scalar with Array (Sabse Simple)**
Ek single number poore array ke har element ke sath calculate ho jata hai.
- `[10, 20, 30] + 5` $\implies$ `[15, 25, 35]`

---

#### **Rule 2: 1D Array with 2D Matrix**
Agar matrix ka shape `(3, 3)` hai aur aap usme `(3,)` ka 1D vector add karte ho:
- NumPy us 1D vector ko har ek row par horizontally stretch karke duplicate kar leta hai.

#### **Broadcasting Match Rule:**
Do dimensions tabhi compatible hote hain jab:
1. Dono dimensions **exact barabar** hon, **YA**
2. Dono me se kisi ek dimension ki value **1** ho.

In [45]:
# 1. Scalar Broadcasting
arr1d = np.array([10, 20, 30])
print("1D Array:", arr1d)
print("Array + 5 (Scalar Broadcast):", arr1d + 5)

print()

# 2. 2D Matrix with 1D Array Broadcasting
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])  # Shape (3, 3)

row_addition = np.array([10, 20, 30])  # Shape (3,)

print("Matrix (3x3):\n", matrix)
print("\nRow to add (3,):\n", row_addition)

# Har row me row_addition add ho jayega
broadcast_result = matrix + row_addition
print("\nResult after Broadcasting:\n", broadcast_result)

1D Array: [10 20 30]
Array + 5 (Scalar Broadcast): [15 25 35]

Matrix (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Row to add (3,):
 [10 20 30]

Result after Broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


### **Assignment**

In [46]:

#! Do arrays a = [10, 20, 30] aur b = [1, 2, 3] ka element-wise addition, subtraction, aur multiplication karein. 
a = np.array([10, 20, 30])  
b = np.array([1, 2, 3])
print("Array a:", a)
print("Array b:", b)
print(f"Element-wise Addition : {a + b}")
print(f"Element-wise Subtraction : {a - b}")
print(f"Element-wise Multiplication : {a * b}")

#! Array [5, 10, 15] ke har element ko scalar 2 se multiply karein (Vectorization). 
c = np.array([5, 10, 15])
print(f"\nOriginal Array : {c}")  
print(f"Each Element Multiplied by 2: {c * 2}")

#! Array [10, 25, 30] ka floor division (//) aur modulo (%) nikaalein scalar 4 ke sath.
d = np.array([10, 25, 30])
print(f"\nOriginal Array : {d}")
print(f"Floor Division by 4 : {d // 4}")
print(f"Modulo by 4 : {d % 4}")

#! Array [1, 2, 3, 4] ke sabhi elements ka square calculate karein using exponent operator ** 2.
e = np.array([1, 2, 3, 4])
print("\nOriginal Array : ", e)
print("Square of Each Element : ", e ** 2)

#! Array [10, 45, 60, 20, 85] par condition lagakar check karein kaun se elements >= 50 hain (Boolean array output).
f = np.array([10, 45, 60, 20, 85])
print("\nOriginal Array : ", f)
print("Elements Greater Than or Equal to 50 : ", f >= 50)

Array a: [10 20 30]
Array b: [1 2 3]
Element-wise Addition : [11 22 33]
Element-wise Subtraction : [ 9 18 27]
Element-wise Multiplication : [10 40 90]

Original Array : [ 5 10 15]
Each Element Multiplied by 2: [10 20 30]

Original Array : [10 25 30]
Floor Division by 4 : [2 6 7]
Modulo by 4 : [2 1 2]

Original Array :  [1 2 3 4]
Square of Each Element :  [ 1  4  9 16]

Original Array :  [10 45 60 20 85]
Elements Greater Than or Equal to 50 :  [False False  True False  True]


In [47]:

#! Usi array se Boolean Indexing use karke sirf passing scores (>= 50) extract karein.
print("Original Array : ", f)
print(f"Passing Scores (>= 50) : {f[f >= 50]}")

#! Ek array se wo numbers filter karein jo 20 se bade hon AUR 80 se chote hon using bitwise &.
print("\nOriginal Array : ", f)
print(f"Numbers Greater Than 20 and Less Than 80 : {f[(f > 20) & (f < 80)]}")

#! Ek array se wo numbers filter karein jo ya toh < 15 hon YA > 75 hon using bitwise |.
print("\nOriginal Array : ", c)
print(f"Numbers Less Than 15 or Greater Than 75 : {f[(f < 15) | (f > 75)]}")

#! Boolean condition ke aage ~ (NOT) operator lagakar output ko invert karein.
print("\nOriginal Array : ", f)
print(f"Inverted Boolean Condition : {~(f >= 50)}")

#! Array [1, 4, 9, 16, 25] ka square root nikaalein using np.sqrt().
g = np.array([1, 4, 9, 16, 25])
print("\nOriginal Array : ", g)
print(f"Square Root of Each Element : {np.sqrt(g)}")

Original Array :  [10 45 60 20 85]
Passing Scores (>= 50) : [60 85]

Original Array :  [10 45 60 20 85]
Numbers Greater Than 20 and Less Than 80 : [45 60]

Original Array :  [ 5 10 15]
Numbers Less Than 15 or Greater Than 75 : [10 85]

Original Array :  [10 45 60 20 85]
Inverted Boolean Condition : [ True  True False  True False]

Original Array :  [ 1  4  9 16 25]
Square Root of Each Element : [1. 2. 3. 4. 5.]


In [48]:

#! Array [-5, 10, -20, 30] ki absolute values nikaalein using np.abs().
h = np.array([-5, 10, -20, 30])
print("\nOriginal Array : ", h)
print(f"Absolute Values of Each Element : {np.abs(h)}")

#! Array [1, 2, 3] ka exponential ($e^x$) aur natural log ($\ln$) calculate karein using np.exp() aur np.log().
i = np.array([1, 2, 3])
print(f"\nOriginal Array : {i}")
print(f"Exponential (e^x) of Each Element : {np.exp(i)}")
print(f"Natural Log (ln) of Each Element : {np.log(i)}")

#! Ek 3x3 matrix me single scalar 10 add karein (Scalar-to-2D Broadcasting). 
j = np.arange(9).reshape(3, 3)
print(f"\nOriginal 3×3 Matrix : \n{j}")
print(f"\nMatrix After Adding Scalar 10 : \n{j + 10}")

#! Ek 3x3 matrix me 1D row vector of shape (3,) add karein (Row-wise Broadcasting).  
print(f"\nOriginal Array : {i}") 
print(f"\nOriginal 3×3 Matrix : \n{j}")
print(f"\nMatrix After Row-wise Broadcasting : \n{j + i}")


Original Array :  [ -5  10 -20  30]
Absolute Values of Each Element : [ 5 10 20 30]

Original Array : [1 2 3]
Exponential (e^x) of Each Element : [ 2.71828183  7.3890561  20.08553692]
Natural Log (ln) of Each Element : [0.         0.69314718 1.09861229]

Original 3×3 Matrix : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Matrix After Adding Scalar 10 : 
[[10 11 12]
 [13 14 15]
 [16 17 18]]

Original Array : [1 2 3]

Original 3×3 Matrix : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Matrix After Row-wise Broadcasting : 
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [49]:

#! Ek 3x3 matrix me column vector of shape (3, 1) add karein (Column-wise Broadcasting).
k = i.reshape(3, 1)
print(f"\nOriginal 3×3 Matrix : \n{j}")
print(f"\nOriginal (3, 1) Column Vector : \n{k}")
print(f"\nMatrix After Column-wise Broadcasting : \n{j + k}")

#! Check karein kya shape (4, 3) aur shape (3,) broadcast ho sakte hain? Reason likhein.
l = np.arange(12).reshape(4, 3)
print(f"\nOriginal 3×1 Matrix : \n{i}")
print(f"\nOriginal 4×3 Matrix : \n{l}")
print(f"\nMatrix After Broadcasting : \n{l + i}")
print("\nReason: The shape (4, 3) can be broadcast with shape (3,) because the last dimension sizes are compatible (3 and 3). The first dimension of the second array is treated as 1, allowing it to be broadcast across the first dimension of the first array.")



Original 3×3 Matrix : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Original (3, 1) Column Vector : 
[[1]
 [2]
 [3]]

Matrix After Column-wise Broadcasting : 
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

Original 3×1 Matrix : 
[1 2 3]

Original 4×3 Matrix : 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Matrix After Broadcasting : 
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]

Reason: The shape (4, 3) can be broadcast with shape (3,) because the last dimension sizes are compatible (3 and 3). The first dimension of the second array is treated as 1, allowing it to be broadcast across the first dimension of the first array.


In [50]:

#! Check karein kya shape (3, 3) aur shape (2,) broadcast ho sakte hain? Code run karke ValueError verify karein.
m = np.array([1, 2])
print(f"\nOriginal 2×1 Matrix : \n{m}")
print(f"\nOriginal 3×3 Matrix : \n{j}")
print("\nAttempting to Broadcast (3, 3) with (2,):")
try:
    result = j + m
    print(f"\nResult after Broadcasting:\n{result}")
except ValueError as e:
    print(f"\nError occurred: {e}")

#! Array [10, 20, 30, 40] par condition lagakar negative numbers ko 0 aur positive ko 1 se replace karein using Boolean masking.
print(f"\nOriginal Array : {a}")
boolean_mask = a > 0 
a[boolean_mask] = 1
print(f"Array after Boolean Masking : {a}")


Original 2×1 Matrix : 
[1 2]

Original 3×3 Matrix : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Attempting to Broadcast (3, 3) with (2,):

Error occurred: operands could not be broadcast together with shapes (3,3) (2,) 

Original Array : [10 20 30]
Array after Boolean Masking : [1 1 1]


In [59]:
 
#! np.where().np.where() use karke ek 1D array se sabhi even numbers ke index positions nikal kar print karein.
n = np.array([10, 15, 20, 25, 30, 35])
print(f"\nOriginal Array : {n}")
even_indices = np.where(n % 2 == 0)[0]
print(f"Indices of Even Numbers: {even_indices}")

#! Ek 2D matrix me jahan bhi value < 0 ho wahan use 0 se replace karein (ReLU logic) using Boolean masking.
o = np.array([[-1, 2, -3], [4, -5, 6]])
bool_mask = o < 0
o[bool_mask] = 0
print(f"\nOriginal 2D Matrix : \n{o}")
print(f"\n2D Matrix after ReLU Logic (Negative Values Replaced with 0): \n{o}")


Original Array : [10 15 20 25 30 35]
Indices of Even Numbers: [0 2 4]

Original 2D Matrix : 
[[0 2 0]
 [4 0 6]]

2D Matrix after ReLU Logic (Negative Values Replaced with 0): 
[[0 2 0]
 [4 0 6]]
