# **Aggregations, Axis Math & Linear Algebra**

Is phase me hum seekhenge ki bade arrays me se summary statistics (Sum, Mean, Min, Max) kaise nikaalte hain, row/column wise calculation kaise karte hain (`axis=0` vs `axis=1`), aur Machine Learning ka core math (Dot Product) kaise perform karte hain.

---

### **1. Basic Summary Statistics (Aggregations)**

Puri matrix ya array ki ek single consolidated value nikalna:

* `np.sum(arr)` : Sabhi numbers ka total sum.
* `np.mean(arr)` : Average (Ausat) calculate karna.
* `np.std(arr)` : Standard Deviation (Data kitna faila hua hai).
* `np.min(arr)` / `np.max(arr)` : Minimum aur Maximum value nikalna.

In [1]:
import numpy as np

data = np.array([12, 45, 67, 89, 23, 56])
print("Data:", data)

print("\n--- Summary Statistics ---")
print("Total Sum:", np.sum(data))
print("Mean (Average):", np.mean(data))
print("Standard Deviation:", np.std(data))
print("Minimum Value:", np.min(data))
print("Maximum Value:", np.max(data))

Data: [12 45 67 89 23 56]

--- Summary Statistics ---
Total Sum: 292
Mean (Average): 48.666666666666664
Standard Deviation: 25.927248643506744
Minimum Value: 12
Maximum Value: 89


### **2. Axis-Based Math (`axis=0` vs `axis=1`)**

2D Table (Matrix) me calculation karte waqt direction define karna mandatory hota hai:

* **`axis=0` (Downwards / Columns ke along):** 
  - Har ek column ke elements par vertically calculation hoti hai.
  - Output har column ka ek answer deta hai.
* **`axis=1` (Across / Rows ke along):** 
  - Har ek row ke elements par horizontally calculation hoti hai.
  - Output har row ka ek answer deta hai.

> **Mental Trick:** `axis=0` collapse rows (columns bachte hain), `axis=1` collapse columns (rows bachti hain).

In [2]:
# 3 Students ke 3 Subjects ke marks (3x3 Matrix)
scores = np.array([
    [80, 85, 90],  # Student 0
    [60, 70, 75],  # Student 1
    [95, 90, 85]   # Student 2
])

print("Marks Matrix (3 Students x 3 Subjects):\n", scores)

# Column-wise sum (axis=0): Har subject ka total
print("\nHar Subject ka Total (axis=0):", np.sum(scores, axis=0))

# Row-wise mean (axis=1): Har student ka average percentage
print("Har Student ka Average (axis=1):", np.mean(scores, axis=1))

Marks Matrix (3 Students x 3 Subjects):
 [[80 85 90]
 [60 70 75]
 [95 90 85]]

Har Subject ka Total (axis=0): [235 245 250]
Har Student ka Average (axis=1): [85.         68.33333333 90.        ]


### **3. Position Finders: `argmin()` & `argmax()`**

Yeh functions values ke bajaye us value ka **Index (Position)** return karte hain.

* **`np.argmax(arr)`:** Sabse badi value kis index par baithi hai.
* **`np.argmin(arr)`:** Sabse choti value kis index par baithi hai.

* **ML Relevance:** Classification models me probabilities di hoti hain (jaise `[0.10, 0.85, 0.05]`); `np.argmax()` batata hai ki prediction class `1` hai.

In [3]:
# Model predictions for 4 classes: Cat, Dog, Bird, Fish
class_probabilities = np.array([0.05, 0.78, 0.12, 0.05])
classes = ["Cat", "Dog", "Bird", "Fish"]

print("Probabilities:", class_probabilities)

# Sabse badi probability ka index
pred_idx = np.argmax(class_probabilities)
print(f"Predicted Class Index: {pred_idx}")
print(f"Final Model Prediction: {classes[pred_idx]}")

Probabilities: [0.05 0.78 0.12 0.05]
Predicted Class Index: 1
Final Model Prediction: Dog


### **4. Linear Algebra Core: Matrix Multiplication (`@` / `np.dot`)**

Machine learning me features aur weights ka multiplication normal `*` se nahi, balki **Dot Product / Matrix Multiplication** se hota hai.

* Element-wise multiply: `A * B` (Dono ke shapes exact same chahiye).
* Matrix Multiplication: `A @ B` ya `np.dot(A, B)`.
  - **Rule:** Matrix A ke Columns ($N$) == Matrix B ki Rows ($N$) hone chahiye.
  - Shape Flow: `(M, N) @ (N, P) -> (M, P)`.

In [4]:
# Matrix A: (2 samples, 3 features)
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Matrix B / Model Weights: (3 features, 2 outputs)
B = np.array([
    [7, 8],
    [9, 1],
    [2, 3]
])

print("Matrix A (2x3):\n", A)
print("\nMatrix B (3x2):\n", B)

# Matrix Multiplication using '@' operator
result = A @ B
print("\nMatrix Multiplication Result (A @ B) -> Shape (2x2):\n", result)

Matrix A (2x3):
 [[1 2 3]
 [4 5 6]]

Matrix B (3x2):
 [[7 8]
 [9 1]
 [2 3]]

Matrix Multiplication Result (A @ B) -> Shape (2x2):
 [[31 19]
 [85 55]]


### **5. Reproducibility & Shuffling (`seed` & `permutation`)**
* `np.random.seed(number)`: Random generation ko lock karta hai taaki har baar run karne par exact same random numbers aayein (Reproducibility).
* `np.random.permutation(arr)`: Array ka data order randomly shuffle karta hai (Dataset shuffling ke liye).

In [5]:
# 1. Setting Seed for consistent results
np.random.seed(42)
rand_nums = np.random.rand(3)
print("Consistent Random Numbers (Seed 42):", rand_nums)

# 2. Shuffling indices/data
indices = np.arange(6)
shuffled_indices = np.random.permutation(indices)
print("Original Indices:", indices)
print("Shuffled Indices for Train/Test split:", shuffled_indices)

Consistent Random Numbers (Seed 42): [0.37454012 0.95071431 0.73199394]
Original Indices: [0 1 2 3 4 5]
Shuffled Indices for Train/Test split: [3 0 1 2 5 4]


### **6. Percentiles & Quartiles (`np.percentile`)**
Data distribution me specific percentage points (25th percentile Q1, 50th median, 75th Q3) nikalne ke liye use hota hai.

In [6]:
dataset = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

# 25th (Q1), 50th (Median), 75th (Q3) percentiles
q1 = np.percentile(dataset, 25)
median = np.percentile(dataset, 50)
q3 = np.percentile(dataset, 75)

print(f"25th Percentile (Q1): {q1}")
print(f"50th Percentile (Median): {median}")
print(f"75th Percentile (Q3): {q3}")
print(f"Interquartile Range (IQR = Q3 - Q1): {q3 - q1}")

25th Percentile (Q1): 22.5
50th Percentile (Median): 35.0
75th Percentile (Q3): 47.5
Interquartile Range (IQR = Q3 - Q1): 25.0


### **7. Matrix Inversion (`np.linalg.inv`)**
Square matrix ka inverse ($A^{-1}$) nikalne ke liye use hota hai.
$$\text{Property: } A @ A^{-1} = I \text{ (Identity Matrix)}$$

In [7]:
square_mat = np.array([[2, 1], 
                       [5, 3]])

# Matrix Inverse
inv_mat = np.linalg.inv(square_mat)
print("Original Matrix (2x2):\n", square_mat)
print("\nInverse Matrix:\n", inv_mat)

# Verification: A @ A_inv should give Identity Matrix
identity_check = np.round(square_mat @ inv_mat)
print("\nA @ Inverse (Identity Matrix):\n", identity_check)

Original Matrix (2x2):
 [[2 1]
 [5 3]]

Inverse Matrix:
 [[ 3. -1.]
 [-5.  2.]]

A @ Inverse (Identity Matrix):
 [[ 1.  0.]
 [-0.  1.]]


### **Assignment**

In [16]:

#! Array [10, 20, 30, 40, 50] ka total sum nikaalein using np.sum().   
ar1 = np.array([10, 20, 30, 40, 50])
print(f"\nOriginal Array : {ar1}")
print(f"Sum of the Array : {np.sum(ar1)}")  

#! Kisi 1D dataset ka mean (average) aur median calculate karein using np.mean() aur np.median(). 
print(f"\nMean of the Array : {np.mean(ar1)}")    
print(f"Median of the Array : {np.median(ar1)}")   

#! Kisi dataset ka standard deviation aur variance nikaalein using np.std() aur np.var().   
print(f"\nStandard Deviation of the Array : {np.std(ar1)}")   
print(f"Variance of the Array : {np.var(ar1)}")   

#! Array se minimum aur maximum value extract karein using np.min() aur np.max().   
print(f"\nMinimum Value of the Array : {np.min(ar1)}")    
print(f"Maximum Value of the Array : {np.max(ar1)}")  

#! Ek 3x4 matrix ka column-wise vertical sum nikaalein using axis=0.   
ar2 = np.arange(12).reshape(3, 4)
print(f"\nOriginal Array : \n{ar2}")
print(f"\nColumn-wise Sum of the 3x4 Matrix : {np.sum(ar2, axis = 0)}")


Original Array : [10 20 30 40 50]
Sum of the Array : 150

Mean of the Array : 30.0
Median of the Array : 30.0

Standard Deviation of the Array : 14.142135623730951
Variance of the Array : 200.0

Minimum Value of the Array : 10
Maximum Value of the Array : 50

Original Array : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Column-wise Sum of the 3x4 Matrix : [12 15 18 21]


In [21]:

#! Ek 3x4 matrix ka row-wise horizontal mean nikaalein using axis=1.  
print(f"\nOriginal Array : \n{ar2}")
print(f"\nRow-wise Sum of the 3x4 Matrix : {np.sum(ar2, axis = 1)}") 

#! Array [15, 80, 45, 95, 30] me sabse badi value ka index pata karein using np.argmax().   
ar3 = np.array([15, 80, 45, 95, 30])
print(f"\nOriginal Array : {ar3}")
print(f"Access the Index of the Maximum Value of the Array : {np.argmax(ar3)}")

#! Usi array me sabse choti value ka index pata karein using np.argmin().   
print(f"Access the Index of the Minimum Value of the Array : {np.argmin(ar3)}")

#! Ek 3x3 matrix me har ek row ka maximum value index nikaalein using np.argmax(axis=1).
ar4 = np.arange(9).reshape(3, 3)
print(f"\nOriginal Array : \n{ar4}")
print(f"\nAccess the Index of the Maximum Value of the Each Row in the Array : {np.argmax(ar4, axis = 1)}")

#! Do vectors [1, 2, 3] aur [4, 5, 6] ka Dot Product calculate karein using np.dot().   
ar5 = np.array([1, 2, 3])
ar6 = np.array([4, 5, 6])
print(f"Dot Product : {np.dot(ar5, ar6)}")


Original Array : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Row-wise Sum of the 3x4 Matrix : [ 6 22 38]

Original Array : [15 80 45 95 30]
Access the Index of the Maximum Value of the Array : 3
Access the Index of the Minimum Value of the Array : 0

Original Array : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Access the Index of the Maximum Value of the Each Row in the Array : [2 2 2]
Dot Product : 32


In [31]:

#! Matrix A (2, 3) aur Matrix B (3, 2) ka matrix multiplication karein using @ operator. 
a = np.arange(11, 17).reshape(2, 3)
b = np.arange(21, 27).reshape(3, 2)
print(f"Matrix A (2, 3) and Matrix B (3, 2) have multiplication using @ : \n{a @ b}")  

#! Verify karein ki agar Matrix A (2, 3) aur Matrix B (2, 3) par @ lagayein toh dimension mismatch error aata hai ya nahi.
c = np.arange(11, 17).reshape(2, 3)
d = np.arange(21, 27).reshape(2, 3)
try:
    print(f"\nMatrix C (2, 3) and Matrix D (2, 3) have multiplication using @ : \n{c @ d}")
except ValueError as e:
    print(f"\nError: {e}")

#! np.random.seed(42) set karein aur 3 random numbers generate karein; dobara run karke verify karein ki numbers same aate hain.
np.random.seed(42)
random_numbers = np.random.randint(1, 10, size=3)
print(f"Random Numbers: \n{random_numbers}")

#! Array np.arange(10) ko randomly shuffle karein using np.random.permutation() (Train/Test split simulation).
ar7 = np.arange(10)
shuffled_ar7 = np.random.permutation(ar7)
print(f"\nOriginal Array: {ar7}")
print(f"Shuffled Array: {shuffled_ar7}")

#! Dataset [10, 20, 30, 40, 50, 60, 70, 80, 90, 100] ka 25th percentile (Q1) aur 75th percentile (Q3) nikaalein using np.percentile().   
dataset = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
q1 = np.percentile(dataset, 25)
q3 = np.percentile(dataset, 75)
print(f"\n25th Percentile (Q1): {q1}")
print(f"75th Percentile (Q3): {q3}")

Matrix A (2, 3) and Matrix B (3, 2) have multiplication using @ : 
[[ 832  868]
 [1039 1084]]

Error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)
Random Numbers: 
[7 4 8]

Original Array: [0 1 2 3 4 5 6 7 8 9]
Shuffled Array: [9 7 0 3 5 8 2 1 6 4]

25th Percentile (Q1): 32.5
75th Percentile (Q3): 77.5


In [41]:

#! Usi dataset ka Interquartile Range (IQR=Q3−Q1) compute karein. 
iqr = q3 - q1
print(f"Interquartile Range (IQR = Q3 - Q1): {iqr}")  

#! Ek square matrix [[4, 7], [2, 6]] ka determinant calculate karein using np.linalg.det(). 
matrix = np.array([[4, 7], [2, 6]])
det = np.linalg.det(matrix)
print(f"\nDeterminant of the matrix: {det}")

#! Usi square matrix ka multiplicative inverse (A −1) calculate karein using np.linalg.inv().   
mut = np.linalg.inv(matrix)
print(f"\nMultiplicative Inverse of the matrix: \n{mut}")

#! Verify karein ki A@A −1 Identity matrix ([[1, 0], [0, 1]]) return karta hai.
identity = matrix @ mut
print(f"\nVerification (A @ A^(-1)): \n{identity}")

#! Ek 1D array [1, 2, 2, 3, 4, 4, 4, 5] se unique elements aur unki frequency/counts nikaalein using np.unique(..., return_counts=True).
array = np.array([1, 2, 2, 3, 4, 4, 4, 5])
unique_elements, counts = np.unique(array, return_counts=True)
print("\nOriginal Array:", array)
print("Unique Elements:", unique_elements)
print("Frequency of Each Element:", counts)

Interquartile Range (IQR = Q3 - Q1): 45.0

Determinant of the matrix: 10.000000000000002

Multiplicative Inverse of the matrix: 
[[ 0.6 -0.7]
 [-0.2  0.4]]

Verification (A @ A^(-1)): 
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]

Original Array: [1 2 2 3 4 4 4 5]
Unique Elements: [1 2 3 4 5]
Frequency of Each Element: [1 2 1 3 1]
